// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteTextDataUsecase is an autogenerated mock type for the DeleteTextDataUsecase type
type DeleteTextDataUsecase struct {
	mock.Mock
}

type DeleteTextDataUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteTextDataUsecase) EXPECT() *DeleteTextDataUsecase_Expecter {
	return &DeleteTextDataUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, textDataID
func (_m *DeleteTextDataUsecase) Execute(ctx context.Context, userID string, textDataID string) error {
	ret := _m.Called(ctx, userID, textDataID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, textDataID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTextDataUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteTextDataUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - textDataID string
func (_e *DeleteTextDataUsecase_Expecter) Execute(ctx interface{}, userID interface{}, textDataID interface{}) *DeleteTextDataUsecase_Execute_Call {
	return &DeleteTextDataUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, textDataID)}
}

func (_c *DeleteTextDataUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, textDataID string)) *DeleteTextDataUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DeleteTextDataUsecase_Execute_Call) Return(_a0 error) *DeleteTextDataUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteTextDataUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, string) error) *DeleteTextDataUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteTextDataUsecase creates a new instance of DeleteTextDataUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteTextDataUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteTextDataUsecase {
	mock := &DeleteTextDataUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
