// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteBinaryDataUsecase is an autogenerated mock type for the DeleteBinaryDataUsecase type
type DeleteBinaryDataUsecase struct {
	mock.Mock
}

type DeleteBinaryDataUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteBinaryDataUsecase) EXPECT() *DeleteBinaryDataUsecase_Expecter {
	return &DeleteBinaryDataUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, binaryDataID
func (_m *DeleteBinaryDataUsecase) Execute(ctx context.Context, userID string, binaryDataID string) error {
	ret := _m.Called(ctx, userID, binaryDataID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, binaryDataID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBinaryDataUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteBinaryDataUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - binaryDataID string
func (_e *DeleteBinaryDataUsecase_Expecter) Execute(ctx interface{}, userID interface{}, binaryDataID interface{}) *DeleteBinaryDataUsecase_Execute_Call {
	return &DeleteBinaryDataUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, binaryDataID)}
}

func (_c *DeleteBinaryDataUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, binaryDataID string)) *DeleteBinaryDataUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DeleteBinaryDataUsecase_Execute_Call) Return(_a0 error) *DeleteBinaryDataUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteBinaryDataUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, string) error) *DeleteBinaryDataUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteBinaryDataUsecase creates a new instance of DeleteBinaryDataUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteBinaryDataUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteBinaryDataUsecase {
	mock := &DeleteBinaryDataUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
