// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/a-blokhin/goph-keeper/internal/model"
)

// ListBinaryDataUsecase is an autogenerated mock type for the ListBinaryDataUsecase type
type ListBinaryDataUsecase struct {
	mock.Mock
}

type ListBinaryDataUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ListBinaryDataUsecase) EXPECT() *ListBinaryDataUsecase_Expecter {
	return &ListBinaryDataUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID
func (_m *ListBinaryDataUsecase) Execute(ctx context.Context, userID string) ([]*model.BinaryData, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*model.BinaryData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.BinaryData, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.BinaryData); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.BinaryData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBinaryDataUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListBinaryDataUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ListBinaryDataUsecase_Expecter) Execute(ctx interface{}, userID interface{}) *ListBinaryDataUsecase_Execute_Call {
	return &ListBinaryDataUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID)}
}

func (_c *ListBinaryDataUsecase_Execute_Call) Run(run func(ctx context.Context, userID string)) *ListBinaryDataUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ListBinaryDataUsecase_Execute_Call) Return(_a0 []*model.BinaryData, _a1 error) *ListBinaryDataUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListBinaryDataUsecase_Execute_Call) RunAndReturn(run func(context.Context, string) ([]*model.BinaryData, error)) *ListBinaryDataUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListBinaryDataUsecase creates a new instance of ListBinaryDataUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListBinaryDataUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListBinaryDataUsecase {
	mock := &ListBinaryDataUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
