// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/a-blokhin/goph-keeper/api/proto"
)

// KeeperServiceClient is an autogenerated mock type for the KeeperServiceClient type
type KeeperServiceClient struct {
	mock.Mock
}

type KeeperServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *KeeperServiceClient) EXPECT() *KeeperServiceClient_Expecter {
	return &KeeperServiceClient_Expecter{mock: &_m.Mock}
}

// CreateBinaryData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) CreateBinaryData(ctx context.Context, in *proto.BinaryDataRequest, opts ...grpc.CallOption) (*proto.BinaryDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateBinaryData")
	}

	var r0 *proto.BinaryDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BinaryDataRequest, ...grpc.CallOption) (*proto.BinaryDataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BinaryDataRequest, ...grpc.CallOption) *proto.BinaryDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BinaryDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.BinaryDataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_CreateBinaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBinaryData'
type KeeperServiceClient_CreateBinaryData_Call struct {
	*mock.Call
}

// CreateBinaryData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.BinaryDataRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) CreateBinaryData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_CreateBinaryData_Call {
	return &KeeperServiceClient_CreateBinaryData_Call{Call: _e.mock.On("CreateBinaryData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_CreateBinaryData_Call) Run(run func(ctx context.Context, in *proto.BinaryDataRequest, opts ...grpc.CallOption)) *KeeperServiceClient_CreateBinaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.BinaryDataRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_CreateBinaryData_Call) Return(_a0 *proto.BinaryDataResponse, _a1 error) *KeeperServiceClient_CreateBinaryData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_CreateBinaryData_Call) RunAndReturn(run func(context.Context, *proto.BinaryDataRequest, ...grpc.CallOption) (*proto.BinaryDataResponse, error)) *KeeperServiceClient_CreateBinaryData_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCard provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) CreateCard(ctx context.Context, in *proto.CardRequest, opts ...grpc.CallOption) (*proto.CardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateCard")
	}

	var r0 *proto.CardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CardRequest, ...grpc.CallOption) (*proto.CardResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CardRequest, ...grpc.CallOption) *proto.CardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.CardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_CreateCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCard'
type KeeperServiceClient_CreateCard_Call struct {
	*mock.Call
}

// CreateCard is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.CardRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) CreateCard(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_CreateCard_Call {
	return &KeeperServiceClient_CreateCard_Call{Call: _e.mock.On("CreateCard",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_CreateCard_Call) Run(run func(ctx context.Context, in *proto.CardRequest, opts ...grpc.CallOption)) *KeeperServiceClient_CreateCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.CardRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_CreateCard_Call) Return(_a0 *proto.CardResponse, _a1 error) *KeeperServiceClient_CreateCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_CreateCard_Call) RunAndReturn(run func(context.Context, *proto.CardRequest, ...grpc.CallOption) (*proto.CardResponse, error)) *KeeperServiceClient_CreateCard_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCredential provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) CreateCredential(ctx context.Context, in *proto.CredentialRequest, opts ...grpc.CallOption) (*proto.CredentialResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredential")
	}

	var r0 *proto.CredentialResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CredentialRequest, ...grpc.CallOption) (*proto.CredentialResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CredentialRequest, ...grpc.CallOption) *proto.CredentialResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CredentialResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.CredentialRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_CreateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCredential'
type KeeperServiceClient_CreateCredential_Call struct {
	*mock.Call
}

// CreateCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.CredentialRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) CreateCredential(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_CreateCredential_Call {
	return &KeeperServiceClient_CreateCredential_Call{Call: _e.mock.On("CreateCredential",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_CreateCredential_Call) Run(run func(ctx context.Context, in *proto.CredentialRequest, opts ...grpc.CallOption)) *KeeperServiceClient_CreateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.CredentialRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_CreateCredential_Call) Return(_a0 *proto.CredentialResponse, _a1 error) *KeeperServiceClient_CreateCredential_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_CreateCredential_Call) RunAndReturn(run func(context.Context, *proto.CredentialRequest, ...grpc.CallOption) (*proto.CredentialResponse, error)) *KeeperServiceClient_CreateCredential_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTextData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) CreateTextData(ctx context.Context, in *proto.TextDataRequest, opts ...grpc.CallOption) (*proto.TextDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTextData")
	}

	var r0 *proto.TextDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.TextDataRequest, ...grpc.CallOption) (*proto.TextDataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.TextDataRequest, ...grpc.CallOption) *proto.TextDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TextDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.TextDataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_CreateTextData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTextData'
type KeeperServiceClient_CreateTextData_Call struct {
	*mock.Call
}

// CreateTextData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.TextDataRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) CreateTextData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_CreateTextData_Call {
	return &KeeperServiceClient_CreateTextData_Call{Call: _e.mock.On("CreateTextData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_CreateTextData_Call) Run(run func(ctx context.Context, in *proto.TextDataRequest, opts ...grpc.CallOption)) *KeeperServiceClient_CreateTextData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.TextDataRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_CreateTextData_Call) Return(_a0 *proto.TextDataResponse, _a1 error) *KeeperServiceClient_CreateTextData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_CreateTextData_Call) RunAndReturn(run func(context.Context, *proto.TextDataRequest, ...grpc.CallOption) (*proto.TextDataResponse, error)) *KeeperServiceClient_CreateTextData_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBinaryData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) DeleteBinaryData(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption) (*proto.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBinaryData")
	}

	var r0 *proto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) *proto.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_DeleteBinaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBinaryData'
type KeeperServiceClient_DeleteBinaryData_Call struct {
	*mock.Call
}

// DeleteBinaryData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.DeleteRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) DeleteBinaryData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_DeleteBinaryData_Call {
	return &KeeperServiceClient_DeleteBinaryData_Call{Call: _e.mock.On("DeleteBinaryData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_DeleteBinaryData_Call) Run(run func(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption)) *KeeperServiceClient_DeleteBinaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.DeleteRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_DeleteBinaryData_Call) Return(_a0 *proto.DeleteResponse, _a1 error) *KeeperServiceClient_DeleteBinaryData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_DeleteBinaryData_Call) RunAndReturn(run func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)) *KeeperServiceClient_DeleteBinaryData_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCard provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) DeleteCard(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption) (*proto.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCard")
	}

	var r0 *proto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) *proto.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_DeleteCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCard'
type KeeperServiceClient_DeleteCard_Call struct {
	*mock.Call
}

// DeleteCard is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.DeleteRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) DeleteCard(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_DeleteCard_Call {
	return &KeeperServiceClient_DeleteCard_Call{Call: _e.mock.On("DeleteCard",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_DeleteCard_Call) Run(run func(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption)) *KeeperServiceClient_DeleteCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.DeleteRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_DeleteCard_Call) Return(_a0 *proto.DeleteResponse, _a1 error) *KeeperServiceClient_DeleteCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_DeleteCard_Call) RunAndReturn(run func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)) *KeeperServiceClient_DeleteCard_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCredential provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) DeleteCredential(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption) (*proto.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCredential")
	}

	var r0 *proto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) *proto.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_DeleteCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCredential'
type KeeperServiceClient_DeleteCredential_Call struct {
	*mock.Call
}

// DeleteCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.DeleteRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) DeleteCredential(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_DeleteCredential_Call {
	return &KeeperServiceClient_DeleteCredential_Call{Call: _e.mock.On("DeleteCredential",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_DeleteCredential_Call) Run(run func(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption)) *KeeperServiceClient_DeleteCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.DeleteRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_DeleteCredential_Call) Return(_a0 *proto.DeleteResponse, _a1 error) *KeeperServiceClient_DeleteCredential_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_DeleteCredential_Call) RunAndReturn(run func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)) *KeeperServiceClient_DeleteCredential_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTextData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) DeleteTextData(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption) (*proto.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTextData")
	}

	var r0 *proto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) *proto.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_DeleteTextData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTextData'
type KeeperServiceClient_DeleteTextData_Call struct {
	*mock.Call
}

// DeleteTextData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.DeleteRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) DeleteTextData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_DeleteTextData_Call {
	return &KeeperServiceClient_DeleteTextData_Call{Call: _e.mock.On("DeleteTextData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_DeleteTextData_Call) Run(run func(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption)) *KeeperServiceClient_DeleteTextData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.DeleteRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_DeleteTextData_Call) Return(_a0 *proto.DeleteResponse, _a1 error) *KeeperServiceClient_DeleteTextData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_DeleteTextData_Call) RunAndReturn(run func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)) *KeeperServiceClient_DeleteTextData_Call {
	_c.Call.Return(run)
	return _c
}

// GetBinaryData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) GetBinaryData(ctx context.Context, in *proto.GetRequest, opts ...grpc.CallOption) (*proto.BinaryDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBinaryData")
	}

	var r0 *proto.BinaryDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) (*proto.BinaryDataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) *proto.BinaryDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BinaryDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_GetBinaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBinaryData'
type KeeperServiceClient_GetBinaryData_Call struct {
	*mock.Call
}

// GetBinaryData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) GetBinaryData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_GetBinaryData_Call {
	return &KeeperServiceClient_GetBinaryData_Call{Call: _e.mock.On("GetBinaryData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_GetBinaryData_Call) Run(run func(ctx context.Context, in *proto.GetRequest, opts ...grpc.CallOption)) *KeeperServiceClient_GetBinaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_GetBinaryData_Call) Return(_a0 *proto.BinaryDataResponse, _a1 error) *KeeperServiceClient_GetBinaryData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_GetBinaryData_Call) RunAndReturn(run func(context.Context, *proto.GetRequest, ...grpc.CallOption) (*proto.BinaryDataResponse, error)) *KeeperServiceClient_GetBinaryData_Call {
	_c.Call.Return(run)
	return _c
}

// GetCard provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) GetCard(ctx context.Context, in *proto.GetRequest, opts ...grpc.CallOption) (*proto.CardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCard")
	}

	var r0 *proto.CardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) (*proto.CardResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) *proto.CardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_GetCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCard'
type KeeperServiceClient_GetCard_Call struct {
	*mock.Call
}

// GetCard is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) GetCard(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_GetCard_Call {
	return &KeeperServiceClient_GetCard_Call{Call: _e.mock.On("GetCard",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_GetCard_Call) Run(run func(ctx context.Context, in *proto.GetRequest, opts ...grpc.CallOption)) *KeeperServiceClient_GetCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_GetCard_Call) Return(_a0 *proto.CardResponse, _a1 error) *KeeperServiceClient_GetCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_GetCard_Call) RunAndReturn(run func(context.Context, *proto.GetRequest, ...grpc.CallOption) (*proto.CardResponse, error)) *KeeperServiceClient_GetCard_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredential provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) GetCredential(ctx context.Context, in *proto.GetRequest, opts ...grpc.CallOption) (*proto.CredentialResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCredential")
	}

	var r0 *proto.CredentialResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) (*proto.CredentialResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) *proto.CredentialResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CredentialResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_GetCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredential'
type KeeperServiceClient_GetCredential_Call struct {
	*mock.Call
}

// GetCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) GetCredential(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_GetCredential_Call {
	return &KeeperServiceClient_GetCredential_Call{Call: _e.mock.On("GetCredential",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_GetCredential_Call) Run(run func(ctx context.Context, in *proto.GetRequest, opts ...grpc.CallOption)) *KeeperServiceClient_GetCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_GetCredential_Call) Return(_a0 *proto.CredentialResponse, _a1 error) *KeeperServiceClient_GetCredential_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_GetCredential_Call) RunAndReturn(run func(context.Context, *proto.GetRequest, ...grpc.CallOption) (*proto.CredentialResponse, error)) *KeeperServiceClient_GetCredential_Call {
	_c.Call.Return(run)
	return _c
}

// GetTextData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) GetTextData(ctx context.Context, in *proto.GetRequest, opts ...grpc.CallOption) (*proto.TextDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTextData")
	}

	var r0 *proto.TextDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) (*proto.TextDataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) *proto.TextDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TextDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_GetTextData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTextData'
type KeeperServiceClient_GetTextData_Call struct {
	*mock.Call
}

// GetTextData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) GetTextData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_GetTextData_Call {
	return &KeeperServiceClient_GetTextData_Call{Call: _e.mock.On("GetTextData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_GetTextData_Call) Run(run func(ctx context.Context, in *proto.GetRequest, opts ...grpc.CallOption)) *KeeperServiceClient_GetTextData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_GetTextData_Call) Return(_a0 *proto.TextDataResponse, _a1 error) *KeeperServiceClient_GetTextData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_GetTextData_Call) RunAndReturn(run func(context.Context, *proto.GetRequest, ...grpc.CallOption) (*proto.TextDataResponse, error)) *KeeperServiceClient_GetTextData_Call {
	_c.Call.Return(run)
	return _c
}

// ListBinaryData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) ListBinaryData(ctx context.Context, in *proto.ListBinaryDataRequest, opts ...grpc.CallOption) (*proto.BinaryDataListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListBinaryData")
	}

	var r0 *proto.BinaryDataListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListBinaryDataRequest, ...grpc.CallOption) (*proto.BinaryDataListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListBinaryDataRequest, ...grpc.CallOption) *proto.BinaryDataListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BinaryDataListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.ListBinaryDataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_ListBinaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBinaryData'
type KeeperServiceClient_ListBinaryData_Call struct {
	*mock.Call
}

// ListBinaryData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.ListBinaryDataRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) ListBinaryData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_ListBinaryData_Call {
	return &KeeperServiceClient_ListBinaryData_Call{Call: _e.mock.On("ListBinaryData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_ListBinaryData_Call) Run(run func(ctx context.Context, in *proto.ListBinaryDataRequest, opts ...grpc.CallOption)) *KeeperServiceClient_ListBinaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.ListBinaryDataRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_ListBinaryData_Call) Return(_a0 *proto.BinaryDataListResponse, _a1 error) *KeeperServiceClient_ListBinaryData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_ListBinaryData_Call) RunAndReturn(run func(context.Context, *proto.ListBinaryDataRequest, ...grpc.CallOption) (*proto.BinaryDataListResponse, error)) *KeeperServiceClient_ListBinaryData_Call {
	_c.Call.Return(run)
	return _c
}

// ListCards provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) ListCards(ctx context.Context, in *proto.ListCardsRequest, opts ...grpc.CallOption) (*proto.CardsListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListCards")
	}

	var r0 *proto.CardsListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListCardsRequest, ...grpc.CallOption) (*proto.CardsListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListCardsRequest, ...grpc.CallOption) *proto.CardsListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CardsListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.ListCardsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_ListCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCards'
type KeeperServiceClient_ListCards_Call struct {
	*mock.Call
}

// ListCards is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.ListCardsRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) ListCards(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_ListCards_Call {
	return &KeeperServiceClient_ListCards_Call{Call: _e.mock.On("ListCards",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_ListCards_Call) Run(run func(ctx context.Context, in *proto.ListCardsRequest, opts ...grpc.CallOption)) *KeeperServiceClient_ListCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.ListCardsRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_ListCards_Call) Return(_a0 *proto.CardsListResponse, _a1 error) *KeeperServiceClient_ListCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_ListCards_Call) RunAndReturn(run func(context.Context, *proto.ListCardsRequest, ...grpc.CallOption) (*proto.CardsListResponse, error)) *KeeperServiceClient_ListCards_Call {
	_c.Call.Return(run)
	return _c
}

// ListCredentials provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) ListCredentials(ctx context.Context, in *proto.ListCredentialsRequest, opts ...grpc.CallOption) (*proto.CredentialsListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListCredentials")
	}

	var r0 *proto.CredentialsListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListCredentialsRequest, ...grpc.CallOption) (*proto.CredentialsListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListCredentialsRequest, ...grpc.CallOption) *proto.CredentialsListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CredentialsListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.ListCredentialsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_ListCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCredentials'
type KeeperServiceClient_ListCredentials_Call struct {
	*mock.Call
}

// ListCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.ListCredentialsRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) ListCredentials(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_ListCredentials_Call {
	return &KeeperServiceClient_ListCredentials_Call{Call: _e.mock.On("ListCredentials",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_ListCredentials_Call) Run(run func(ctx context.Context, in *proto.ListCredentialsRequest, opts ...grpc.CallOption)) *KeeperServiceClient_ListCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.ListCredentialsRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_ListCredentials_Call) Return(_a0 *proto.CredentialsListResponse, _a1 error) *KeeperServiceClient_ListCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_ListCredentials_Call) RunAndReturn(run func(context.Context, *proto.ListCredentialsRequest, ...grpc.CallOption) (*proto.CredentialsListResponse, error)) *KeeperServiceClient_ListCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// ListTextData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) ListTextData(ctx context.Context, in *proto.ListTextDataRequest, opts ...grpc.CallOption) (*proto.TextDataListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListTextData")
	}

	var r0 *proto.TextDataListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListTextDataRequest, ...grpc.CallOption) (*proto.TextDataListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListTextDataRequest, ...grpc.CallOption) *proto.TextDataListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TextDataListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.ListTextDataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_ListTextData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTextData'
type KeeperServiceClient_ListTextData_Call struct {
	*mock.Call
}

// ListTextData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.ListTextDataRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) ListTextData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_ListTextData_Call {
	return &KeeperServiceClient_ListTextData_Call{Call: _e.mock.On("ListTextData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_ListTextData_Call) Run(run func(ctx context.Context, in *proto.ListTextDataRequest, opts ...grpc.CallOption)) *KeeperServiceClient_ListTextData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.ListTextDataRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_ListTextData_Call) Return(_a0 *proto.TextDataListResponse, _a1 error) *KeeperServiceClient_ListTextData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_ListTextData_Call) RunAndReturn(run func(context.Context, *proto.ListTextDataRequest, ...grpc.CallOption) (*proto.TextDataListResponse, error)) *KeeperServiceClient_ListTextData_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) Login(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption) (*proto.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *proto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) *proto.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type KeeperServiceClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.LoginRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_Login_Call {
	return &KeeperServiceClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_Login_Call) Run(run func(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption)) *KeeperServiceClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_Login_Call) Return(_a0 *proto.LoginResponse, _a1 error) *KeeperServiceClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_Login_Call) RunAndReturn(run func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)) *KeeperServiceClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) Register(ctx context.Context, in *proto.RegisterRequest, opts ...grpc.CallOption) (*proto.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *proto.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) (*proto.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) *proto.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type KeeperServiceClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.RegisterRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) Register(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_Register_Call {
	return &KeeperServiceClient_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_Register_Call) Run(run func(ctx context.Context, in *proto.RegisterRequest, opts ...grpc.CallOption)) *KeeperServiceClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.RegisterRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_Register_Call) Return(_a0 *proto.RegisterResponse, _a1 error) *KeeperServiceClient_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_Register_Call) RunAndReturn(run func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) (*proto.RegisterResponse, error)) *KeeperServiceClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) Sync(ctx context.Context, in *proto.SyncRequest, opts ...grpc.CallOption) (*proto.SyncResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 *proto.SyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.SyncRequest, ...grpc.CallOption) (*proto.SyncResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.SyncRequest, ...grpc.CallOption) *proto.SyncResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.SyncRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type KeeperServiceClient_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.SyncRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) Sync(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_Sync_Call {
	return &KeeperServiceClient_Sync_Call{Call: _e.mock.On("Sync",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_Sync_Call) Run(run func(ctx context.Context, in *proto.SyncRequest, opts ...grpc.CallOption)) *KeeperServiceClient_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.SyncRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_Sync_Call) Return(_a0 *proto.SyncResponse, _a1 error) *KeeperServiceClient_Sync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_Sync_Call) RunAndReturn(run func(context.Context, *proto.SyncRequest, ...grpc.CallOption) (*proto.SyncResponse, error)) *KeeperServiceClient_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBinaryData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) UpdateBinaryData(ctx context.Context, in *proto.UpdateBinaryDataRequest, opts ...grpc.CallOption) (*proto.BinaryDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBinaryData")
	}

	var r0 *proto.BinaryDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateBinaryDataRequest, ...grpc.CallOption) (*proto.BinaryDataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateBinaryDataRequest, ...grpc.CallOption) *proto.BinaryDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BinaryDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateBinaryDataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_UpdateBinaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBinaryData'
type KeeperServiceClient_UpdateBinaryData_Call struct {
	*mock.Call
}

// UpdateBinaryData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UpdateBinaryDataRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) UpdateBinaryData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_UpdateBinaryData_Call {
	return &KeeperServiceClient_UpdateBinaryData_Call{Call: _e.mock.On("UpdateBinaryData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_UpdateBinaryData_Call) Run(run func(ctx context.Context, in *proto.UpdateBinaryDataRequest, opts ...grpc.CallOption)) *KeeperServiceClient_UpdateBinaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UpdateBinaryDataRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_UpdateBinaryData_Call) Return(_a0 *proto.BinaryDataResponse, _a1 error) *KeeperServiceClient_UpdateBinaryData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_UpdateBinaryData_Call) RunAndReturn(run func(context.Context, *proto.UpdateBinaryDataRequest, ...grpc.CallOption) (*proto.BinaryDataResponse, error)) *KeeperServiceClient_UpdateBinaryData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCard provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) UpdateCard(ctx context.Context, in *proto.UpdateCardRequest, opts ...grpc.CallOption) (*proto.CardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCard")
	}

	var r0 *proto.CardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateCardRequest, ...grpc.CallOption) (*proto.CardResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateCardRequest, ...grpc.CallOption) *proto.CardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateCardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_UpdateCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCard'
type KeeperServiceClient_UpdateCard_Call struct {
	*mock.Call
}

// UpdateCard is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UpdateCardRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) UpdateCard(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_UpdateCard_Call {
	return &KeeperServiceClient_UpdateCard_Call{Call: _e.mock.On("UpdateCard",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_UpdateCard_Call) Run(run func(ctx context.Context, in *proto.UpdateCardRequest, opts ...grpc.CallOption)) *KeeperServiceClient_UpdateCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UpdateCardRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_UpdateCard_Call) Return(_a0 *proto.CardResponse, _a1 error) *KeeperServiceClient_UpdateCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_UpdateCard_Call) RunAndReturn(run func(context.Context, *proto.UpdateCardRequest, ...grpc.CallOption) (*proto.CardResponse, error)) *KeeperServiceClient_UpdateCard_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCredential provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) UpdateCredential(ctx context.Context, in *proto.UpdateCredentialRequest, opts ...grpc.CallOption) (*proto.CredentialResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCredential")
	}

	var r0 *proto.CredentialResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateCredentialRequest, ...grpc.CallOption) (*proto.CredentialResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateCredentialRequest, ...grpc.CallOption) *proto.CredentialResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CredentialResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateCredentialRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_UpdateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCredential'
type KeeperServiceClient_UpdateCredential_Call struct {
	*mock.Call
}

// UpdateCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UpdateCredentialRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) UpdateCredential(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_UpdateCredential_Call {
	return &KeeperServiceClient_UpdateCredential_Call{Call: _e.mock.On("UpdateCredential",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_UpdateCredential_Call) Run(run func(ctx context.Context, in *proto.UpdateCredentialRequest, opts ...grpc.CallOption)) *KeeperServiceClient_UpdateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UpdateCredentialRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_UpdateCredential_Call) Return(_a0 *proto.CredentialResponse, _a1 error) *KeeperServiceClient_UpdateCredential_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_UpdateCredential_Call) RunAndReturn(run func(context.Context, *proto.UpdateCredentialRequest, ...grpc.CallOption) (*proto.CredentialResponse, error)) *KeeperServiceClient_UpdateCredential_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTextData provides a mock function with given fields: ctx, in, opts
func (_m *KeeperServiceClient) UpdateTextData(ctx context.Context, in *proto.UpdateTextDataRequest, opts ...grpc.CallOption) (*proto.TextDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTextData")
	}

	var r0 *proto.TextDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateTextDataRequest, ...grpc.CallOption) (*proto.TextDataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateTextDataRequest, ...grpc.CallOption) *proto.TextDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TextDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateTextDataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeeperServiceClient_UpdateTextData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTextData'
type KeeperServiceClient_UpdateTextData_Call struct {
	*mock.Call
}

// UpdateTextData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UpdateTextDataRequest
//   - opts ...grpc.CallOption
func (_e *KeeperServiceClient_Expecter) UpdateTextData(ctx interface{}, in interface{}, opts ...interface{}) *KeeperServiceClient_UpdateTextData_Call {
	return &KeeperServiceClient_UpdateTextData_Call{Call: _e.mock.On("UpdateTextData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *KeeperServiceClient_UpdateTextData_Call) Run(run func(ctx context.Context, in *proto.UpdateTextDataRequest, opts ...grpc.CallOption)) *KeeperServiceClient_UpdateTextData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UpdateTextDataRequest), variadicArgs...)
	})
	return _c
}

func (_c *KeeperServiceClient_UpdateTextData_Call) Return(_a0 *proto.TextDataResponse, _a1 error) *KeeperServiceClient_UpdateTextData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeeperServiceClient_UpdateTextData_Call) RunAndReturn(run func(context.Context, *proto.UpdateTextDataRequest, ...grpc.CallOption) (*proto.TextDataResponse, error)) *KeeperServiceClient_UpdateTextData_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeeperServiceClient creates a new instance of KeeperServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeeperServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeeperServiceClient {
	mock := &KeeperServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
