// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/a-blokhin/goph-keeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// BinaryDataRepository is an autogenerated mock type for the BinaryDataRepository type
type BinaryDataRepository struct {
	mock.Mock
}

type BinaryDataRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BinaryDataRepository) EXPECT() *BinaryDataRepository_Expecter {
	return &BinaryDataRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, binaryData
func (_m *BinaryDataRepository) Create(ctx context.Context, binaryData *model.BinaryData) error {
	ret := _m.Called(ctx, binaryData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.BinaryData) error); ok {
		r0 = rf(ctx, binaryData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BinaryDataRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BinaryDataRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - binaryData *model.BinaryData
func (_e *BinaryDataRepository_Expecter) Create(ctx interface{}, binaryData interface{}) *BinaryDataRepository_Create_Call {
	return &BinaryDataRepository_Create_Call{Call: _e.mock.On("Create", ctx, binaryData)}
}

func (_c *BinaryDataRepository_Create_Call) Run(run func(ctx context.Context, binaryData *model.BinaryData)) *BinaryDataRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.BinaryData))
	})
	return _c
}

func (_c *BinaryDataRepository_Create_Call) Return(_a0 error) *BinaryDataRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BinaryDataRepository_Create_Call) RunAndReturn(run func(context.Context, *model.BinaryData) error) *BinaryDataRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BinaryDataRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BinaryDataRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BinaryDataRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BinaryDataRepository_Expecter) Delete(ctx interface{}, id interface{}) *BinaryDataRepository_Delete_Call {
	return &BinaryDataRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *BinaryDataRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *BinaryDataRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BinaryDataRepository_Delete_Call) Return(_a0 error) *BinaryDataRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BinaryDataRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *BinaryDataRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BinaryDataRepository) GetByID(ctx context.Context, id string) (*model.BinaryData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.BinaryData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.BinaryData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.BinaryData); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BinaryData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BinaryDataRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type BinaryDataRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BinaryDataRepository_Expecter) GetByID(ctx interface{}, id interface{}) *BinaryDataRepository_GetByID_Call {
	return &BinaryDataRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *BinaryDataRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *BinaryDataRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BinaryDataRepository_GetByID_Call) Return(_a0 *model.BinaryData, _a1 error) *BinaryDataRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BinaryDataRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.BinaryData, error)) *BinaryDataRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *BinaryDataRepository) GetByUserID(ctx context.Context, userID string) ([]*model.BinaryData, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.BinaryData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.BinaryData, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.BinaryData); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.BinaryData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BinaryDataRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type BinaryDataRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *BinaryDataRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *BinaryDataRepository_GetByUserID_Call {
	return &BinaryDataRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *BinaryDataRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *BinaryDataRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BinaryDataRepository_GetByUserID_Call) Return(_a0 []*model.BinaryData, _a1 error) *BinaryDataRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BinaryDataRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*model.BinaryData, error)) *BinaryDataRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, binaryData
func (_m *BinaryDataRepository) Update(ctx context.Context, binaryData *model.BinaryData) error {
	ret := _m.Called(ctx, binaryData)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.BinaryData) error); ok {
		r0 = rf(ctx, binaryData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BinaryDataRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BinaryDataRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - binaryData *model.BinaryData
func (_e *BinaryDataRepository_Expecter) Update(ctx interface{}, binaryData interface{}) *BinaryDataRepository_Update_Call {
	return &BinaryDataRepository_Update_Call{Call: _e.mock.On("Update", ctx, binaryData)}
}

func (_c *BinaryDataRepository_Update_Call) Run(run func(ctx context.Context, binaryData *model.BinaryData)) *BinaryDataRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.BinaryData))
	})
	return _c
}

func (_c *BinaryDataRepository_Update_Call) Return(_a0 error) *BinaryDataRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BinaryDataRepository_Update_Call) RunAndReturn(run func(context.Context, *model.BinaryData) error) *BinaryDataRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewBinaryDataRepository creates a new instance of BinaryDataRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBinaryDataRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BinaryDataRepository {
	mock := &BinaryDataRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
