// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/a-blokhin/goph-keeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// CardRepository is an autogenerated mock type for the CardRepository type
type CardRepository struct {
	mock.Mock
}

type CardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CardRepository) EXPECT() *CardRepository_Expecter {
	return &CardRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, card
func (_m *CardRepository) Create(ctx context.Context, card *model.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - card *model.Card
func (_e *CardRepository_Expecter) Create(ctx interface{}, card interface{}) *CardRepository_Create_Call {
	return &CardRepository_Create_Call{Call: _e.mock.On("Create", ctx, card)}
}

func (_c *CardRepository_Create_Call) Run(run func(ctx context.Context, card *model.Card)) *CardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Card))
	})
	return _c
}

func (_c *CardRepository_Create_Call) Return(_a0 error) *CardRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Card) error) *CardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CardRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CardRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CardRepository_Expecter) Delete(ctx interface{}, id interface{}) *CardRepository_Delete_Call {
	return &CardRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CardRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *CardRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CardRepository_Delete_Call) Return(_a0 error) *CardRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *CardRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CardRepository) GetByID(ctx context.Context, id string) (*model.Card, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Card, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Card); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CardRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CardRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CardRepository_GetByID_Call {
	return &CardRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CardRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *CardRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CardRepository_GetByID_Call) Return(_a0 *model.Card, _a1 error) *CardRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.Card, error)) *CardRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *CardRepository) GetByUserID(ctx context.Context, userID string) ([]*model.Card, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Card, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Card); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type CardRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CardRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *CardRepository_GetByUserID_Call {
	return &CardRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *CardRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *CardRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CardRepository_GetByUserID_Call) Return(_a0 []*model.Card, _a1 error) *CardRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*model.Card, error)) *CardRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, card
func (_m *CardRepository) Update(ctx context.Context, card *model.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - card *model.Card
func (_e *CardRepository_Expecter) Update(ctx interface{}, card interface{}) *CardRepository_Update_Call {
	return &CardRepository_Update_Call{Call: _e.mock.On("Update", ctx, card)}
}

func (_c *CardRepository_Update_Call) Run(run func(ctx context.Context, card *model.Card)) *CardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Card))
	})
	return _c
}

func (_c *CardRepository_Update_Call) Return(_a0 error) *CardRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Card) error) *CardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCardRepository creates a new instance of CardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardRepository {
	mock := &CardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
