// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/a-blokhin/goph-keeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// CredentialRepository is an autogenerated mock type for the CredentialRepository type
type CredentialRepository struct {
	mock.Mock
}

type CredentialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialRepository) EXPECT() *CredentialRepository_Expecter {
	return &CredentialRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, credential
func (_m *CredentialRepository) Create(ctx context.Context, credential *model.Credential) error {
	ret := _m.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Credential) error); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CredentialRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CredentialRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *model.Credential
func (_e *CredentialRepository_Expecter) Create(ctx interface{}, credential interface{}) *CredentialRepository_Create_Call {
	return &CredentialRepository_Create_Call{Call: _e.mock.On("Create", ctx, credential)}
}

func (_c *CredentialRepository_Create_Call) Run(run func(ctx context.Context, credential *model.Credential)) *CredentialRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Credential))
	})
	return _c
}

func (_c *CredentialRepository_Create_Call) Return(_a0 error) *CredentialRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CredentialRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Credential) error) *CredentialRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CredentialRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CredentialRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CredentialRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CredentialRepository_Expecter) Delete(ctx interface{}, id interface{}) *CredentialRepository_Delete_Call {
	return &CredentialRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CredentialRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *CredentialRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CredentialRepository_Delete_Call) Return(_a0 error) *CredentialRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CredentialRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *CredentialRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CredentialRepository) GetByID(ctx context.Context, id string) (*model.Credential, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Credential, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Credential); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CredentialRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CredentialRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CredentialRepository_GetByID_Call {
	return &CredentialRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CredentialRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *CredentialRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CredentialRepository_GetByID_Call) Return(_a0 *model.Credential, _a1 error) *CredentialRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CredentialRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.Credential, error)) *CredentialRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *CredentialRepository) GetByUserID(ctx context.Context, userID string) ([]*model.Credential, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Credential, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Credential); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type CredentialRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CredentialRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *CredentialRepository_GetByUserID_Call {
	return &CredentialRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *CredentialRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *CredentialRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CredentialRepository_GetByUserID_Call) Return(_a0 []*model.Credential, _a1 error) *CredentialRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CredentialRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*model.Credential, error)) *CredentialRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, credential
func (_m *CredentialRepository) Update(ctx context.Context, credential *model.Credential) error {
	ret := _m.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Credential) error); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CredentialRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CredentialRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *model.Credential
func (_e *CredentialRepository_Expecter) Update(ctx interface{}, credential interface{}) *CredentialRepository_Update_Call {
	return &CredentialRepository_Update_Call{Call: _e.mock.On("Update", ctx, credential)}
}

func (_c *CredentialRepository_Update_Call) Run(run func(ctx context.Context, credential *model.Credential)) *CredentialRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Credential))
	})
	return _c
}

func (_c *CredentialRepository_Update_Call) Return(_a0 error) *CredentialRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CredentialRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Credential) error) *CredentialRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCredentialRepository creates a new instance of CredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialRepository {
	mock := &CredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
