// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/a-blokhin/goph-keeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TextDataRepository is an autogenerated mock type for the TextDataRepository type
type TextDataRepository struct {
	mock.Mock
}

type TextDataRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TextDataRepository) EXPECT() *TextDataRepository_Expecter {
	return &TextDataRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, textData
func (_m *TextDataRepository) Create(ctx context.Context, textData *model.TextData) error {
	ret := _m.Called(ctx, textData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TextData) error); ok {
		r0 = rf(ctx, textData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TextDataRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TextDataRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - textData *model.TextData
func (_e *TextDataRepository_Expecter) Create(ctx interface{}, textData interface{}) *TextDataRepository_Create_Call {
	return &TextDataRepository_Create_Call{Call: _e.mock.On("Create", ctx, textData)}
}

func (_c *TextDataRepository_Create_Call) Run(run func(ctx context.Context, textData *model.TextData)) *TextDataRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.TextData))
	})
	return _c
}

func (_c *TextDataRepository_Create_Call) Return(_a0 error) *TextDataRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TextDataRepository_Create_Call) RunAndReturn(run func(context.Context, *model.TextData) error) *TextDataRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TextDataRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TextDataRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TextDataRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TextDataRepository_Expecter) Delete(ctx interface{}, id interface{}) *TextDataRepository_Delete_Call {
	return &TextDataRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TextDataRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *TextDataRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TextDataRepository_Delete_Call) Return(_a0 error) *TextDataRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TextDataRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *TextDataRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TextDataRepository) GetByID(ctx context.Context, id string) (*model.TextData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.TextData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.TextData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.TextData); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TextData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TextDataRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TextDataRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TextDataRepository_Expecter) GetByID(ctx interface{}, id interface{}) *TextDataRepository_GetByID_Call {
	return &TextDataRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TextDataRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *TextDataRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TextDataRepository_GetByID_Call) Return(_a0 *model.TextData, _a1 error) *TextDataRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TextDataRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.TextData, error)) *TextDataRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *TextDataRepository) GetByUserID(ctx context.Context, userID string) ([]*model.TextData, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.TextData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.TextData, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.TextData); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TextData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TextDataRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type TextDataRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *TextDataRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *TextDataRepository_GetByUserID_Call {
	return &TextDataRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *TextDataRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *TextDataRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TextDataRepository_GetByUserID_Call) Return(_a0 []*model.TextData, _a1 error) *TextDataRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TextDataRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*model.TextData, error)) *TextDataRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, textData
func (_m *TextDataRepository) Update(ctx context.Context, textData *model.TextData) error {
	ret := _m.Called(ctx, textData)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TextData) error); ok {
		r0 = rf(ctx, textData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TextDataRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TextDataRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - textData *model.TextData
func (_e *TextDataRepository_Expecter) Update(ctx interface{}, textData interface{}) *TextDataRepository_Update_Call {
	return &TextDataRepository_Update_Call{Call: _e.mock.On("Update", ctx, textData)}
}

func (_c *TextDataRepository_Update_Call) Run(run func(ctx context.Context, textData *model.TextData)) *TextDataRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.TextData))
	})
	return _c
}

func (_c *TextDataRepository_Update_Call) Return(_a0 error) *TextDataRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TextDataRepository_Update_Call) RunAndReturn(run func(context.Context, *model.TextData) error) *TextDataRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTextDataRepository creates a new instance of TextDataRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTextDataRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TextDataRepository {
	mock := &TextDataRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
