// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/a-blokhin/goph-keeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// GetBinaryDataUsecase is an autogenerated mock type for the GetBinaryDataUsecase type
type GetBinaryDataUsecase struct {
	mock.Mock
}

type GetBinaryDataUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetBinaryDataUsecase) EXPECT() *GetBinaryDataUsecase_Expecter {
	return &GetBinaryDataUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, id
func (_m *GetBinaryDataUsecase) Execute(ctx context.Context, userID string, id string) (*model.BinaryData, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *model.BinaryData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.BinaryData, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.BinaryData); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BinaryData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBinaryDataUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetBinaryDataUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *GetBinaryDataUsecase_Expecter) Execute(ctx interface{}, userID interface{}, id interface{}) *GetBinaryDataUsecase_Execute_Call {
	return &GetBinaryDataUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, id)}
}

func (_c *GetBinaryDataUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, id string)) *GetBinaryDataUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *GetBinaryDataUsecase_Execute_Call) Return(_a0 *model.BinaryData, _a1 error) *GetBinaryDataUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetBinaryDataUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, string) (*model.BinaryData, error)) *GetBinaryDataUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetBinaryDataUsecase creates a new instance of GetBinaryDataUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetBinaryDataUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetBinaryDataUsecase {
	mock := &GetBinaryDataUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
