// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/a-blokhin/goph-keeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UpdateCredentialUsecase is an autogenerated mock type for the UpdateCredentialUsecase type
type UpdateCredentialUsecase struct {
	mock.Mock
}

type UpdateCredentialUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateCredentialUsecase) EXPECT() *UpdateCredentialUsecase_Expecter {
	return &UpdateCredentialUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, credential
func (_m *UpdateCredentialUsecase) Execute(ctx context.Context, userID string, credential *model.Credential) error {
	ret := _m.Called(ctx, userID, credential)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.Credential) error); ok {
		r0 = rf(ctx, userID, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCredentialUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateCredentialUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - credential *model.Credential
func (_e *UpdateCredentialUsecase_Expecter) Execute(ctx interface{}, userID interface{}, credential interface{}) *UpdateCredentialUsecase_Execute_Call {
	return &UpdateCredentialUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, credential)}
}

func (_c *UpdateCredentialUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, credential *model.Credential)) *UpdateCredentialUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.Credential))
	})
	return _c
}

func (_c *UpdateCredentialUsecase_Execute_Call) Return(_a0 error) *UpdateCredentialUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UpdateCredentialUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, *model.Credential) error) *UpdateCredentialUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdateCredentialUsecase creates a new instance of UpdateCredentialUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateCredentialUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateCredentialUsecase {
	mock := &UpdateCredentialUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
