// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/a-blokhin/goph-keeper/internal/model"
)

// CreateCredentialUsecase is an autogenerated mock type for the CreateCredentialUsecase type
type CreateCredentialUsecase struct {
	mock.Mock
}

type CreateCredentialUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateCredentialUsecase) EXPECT() *CreateCredentialUsecase_Expecter {
	return &CreateCredentialUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, credential
func (_m *CreateCredentialUsecase) Execute(ctx context.Context, userID string, credential *model.Credential) error {
	ret := _m.Called(ctx, userID, credential)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.Credential) error); ok {
		r0 = rf(ctx, userID, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCredentialUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateCredentialUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - credential *model.Credential
func (_e *CreateCredentialUsecase_Expecter) Execute(ctx interface{}, userID interface{}, credential interface{}) *CreateCredentialUsecase_Execute_Call {
	return &CreateCredentialUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, credential)}
}

func (_c *CreateCredentialUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, credential *model.Credential)) *CreateCredentialUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.Credential))
	})
	return _c
}

func (_c *CreateCredentialUsecase_Execute_Call) Return(_a0 error) *CreateCredentialUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreateCredentialUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, *model.Credential) error) *CreateCredentialUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateCredentialUsecase creates a new instance of CreateCredentialUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateCredentialUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateCredentialUsecase {
	mock := &CreateCredentialUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
