// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/a-blokhin/goph-keeper/internal/model"
)

// CreateCardUsecase is an autogenerated mock type for the CreateCardUsecase type
type CreateCardUsecase struct {
	mock.Mock
}

type CreateCardUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateCardUsecase) EXPECT() *CreateCardUsecase_Expecter {
	return &CreateCardUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, card
func (_m *CreateCardUsecase) Execute(ctx context.Context, userID string, card *model.Card) error {
	ret := _m.Called(ctx, userID, card)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.Card) error); ok {
		r0 = rf(ctx, userID, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCardUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateCardUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - card *model.Card
func (_e *CreateCardUsecase_Expecter) Execute(ctx interface{}, userID interface{}, card interface{}) *CreateCardUsecase_Execute_Call {
	return &CreateCardUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, card)}
}

func (_c *CreateCardUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, card *model.Card)) *CreateCardUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.Card))
	})
	return _c
}

func (_c *CreateCardUsecase_Execute_Call) Return(_a0 error) *CreateCardUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreateCardUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, *model.Card) error) *CreateCardUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateCardUsecase creates a new instance of CreateCardUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateCardUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateCardUsecase {
	mock := &CreateCardUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
