// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/proto/keeper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeeperService_Register_FullMethodName         = "/keeper.KeeperService/Register"
	KeeperService_Login_FullMethodName            = "/keeper.KeeperService/Login"
	KeeperService_CreateCredential_FullMethodName = "/keeper.KeeperService/CreateCredential"
	KeeperService_GetCredential_FullMethodName    = "/keeper.KeeperService/GetCredential"
	KeeperService_UpdateCredential_FullMethodName = "/keeper.KeeperService/UpdateCredential"
	KeeperService_DeleteCredential_FullMethodName = "/keeper.KeeperService/DeleteCredential"
	KeeperService_ListCredentials_FullMethodName  = "/keeper.KeeperService/ListCredentials"
	KeeperService_CreateTextData_FullMethodName   = "/keeper.KeeperService/CreateTextData"
	KeeperService_GetTextData_FullMethodName      = "/keeper.KeeperService/GetTextData"
	KeeperService_UpdateTextData_FullMethodName   = "/keeper.KeeperService/UpdateTextData"
	KeeperService_DeleteTextData_FullMethodName   = "/keeper.KeeperService/DeleteTextData"
	KeeperService_ListTextData_FullMethodName     = "/keeper.KeeperService/ListTextData"
	KeeperService_CreateBinaryData_FullMethodName = "/keeper.KeeperService/CreateBinaryData"
	KeeperService_GetBinaryData_FullMethodName    = "/keeper.KeeperService/GetBinaryData"
	KeeperService_UpdateBinaryData_FullMethodName = "/keeper.KeeperService/UpdateBinaryData"
	KeeperService_DeleteBinaryData_FullMethodName = "/keeper.KeeperService/DeleteBinaryData"
	KeeperService_ListBinaryData_FullMethodName   = "/keeper.KeeperService/ListBinaryData"
	KeeperService_CreateCard_FullMethodName       = "/keeper.KeeperService/CreateCard"
	KeeperService_GetCard_FullMethodName          = "/keeper.KeeperService/GetCard"
	KeeperService_UpdateCard_FullMethodName       = "/keeper.KeeperService/UpdateCard"
	KeeperService_DeleteCard_FullMethodName       = "/keeper.KeeperService/DeleteCard"
	KeeperService_ListCards_FullMethodName        = "/keeper.KeeperService/ListCards"
	KeeperService_Sync_FullMethodName             = "/keeper.KeeperService/Sync"
)

// KeeperServiceClient is the client API for KeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeeperServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	CreateCredential(ctx context.Context, in *CredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	GetCredential(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	UpdateCredential(ctx context.Context, in *UpdateCredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	DeleteCredential(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*CredentialsListResponse, error)
	CreateTextData(ctx context.Context, in *TextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error)
	GetTextData(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*TextDataResponse, error)
	UpdateTextData(ctx context.Context, in *UpdateTextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error)
	DeleteTextData(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListTextData(ctx context.Context, in *ListTextDataRequest, opts ...grpc.CallOption) (*TextDataListResponse, error)
	CreateBinaryData(ctx context.Context, in *BinaryDataRequest, opts ...grpc.CallOption) (*BinaryDataResponse, error)
	GetBinaryData(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BinaryDataResponse, error)
	UpdateBinaryData(ctx context.Context, in *UpdateBinaryDataRequest, opts ...grpc.CallOption) (*BinaryDataResponse, error)
	DeleteBinaryData(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListBinaryData(ctx context.Context, in *ListBinaryDataRequest, opts ...grpc.CallOption) (*BinaryDataListResponse, error)
	CreateCard(ctx context.Context, in *CardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	GetCard(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CardResponse, error)
	UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*CardResponse, error)
	DeleteCard(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListCards(ctx context.Context, in *ListCardsRequest, opts ...grpc.CallOption) (*CardsListResponse, error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type keeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeeperServiceClient(cc grpc.ClientConnInterface) KeeperServiceClient {
	return &keeperServiceClient{cc}
}

func (c *keeperServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, KeeperService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, KeeperService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) CreateCredential(ctx context.Context, in *CredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, KeeperService_CreateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) GetCredential(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, KeeperService_GetCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) UpdateCredential(ctx context.Context, in *UpdateCredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, KeeperService_UpdateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DeleteCredential(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, KeeperService_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*CredentialsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialsListResponse)
	err := c.cc.Invoke(ctx, KeeperService_ListCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) CreateTextData(ctx context.Context, in *TextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_CreateTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) GetTextData(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*TextDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_GetTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) UpdateTextData(ctx context.Context, in *UpdateTextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_UpdateTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DeleteTextData(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, KeeperService_DeleteTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) ListTextData(ctx context.Context, in *ListTextDataRequest, opts ...grpc.CallOption) (*TextDataListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDataListResponse)
	err := c.cc.Invoke(ctx, KeeperService_ListTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) CreateBinaryData(ctx context.Context, in *BinaryDataRequest, opts ...grpc.CallOption) (*BinaryDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinaryDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_CreateBinaryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) GetBinaryData(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BinaryDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinaryDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_GetBinaryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) UpdateBinaryData(ctx context.Context, in *UpdateBinaryDataRequest, opts ...grpc.CallOption) (*BinaryDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinaryDataResponse)
	err := c.cc.Invoke(ctx, KeeperService_UpdateBinaryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DeleteBinaryData(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, KeeperService_DeleteBinaryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) ListBinaryData(ctx context.Context, in *ListBinaryDataRequest, opts ...grpc.CallOption) (*BinaryDataListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinaryDataListResponse)
	err := c.cc.Invoke(ctx, KeeperService_ListBinaryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) CreateCard(ctx context.Context, in *CardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, KeeperService_CreateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) GetCard(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, KeeperService_GetCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, KeeperService_UpdateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) DeleteCard(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, KeeperService_DeleteCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) ListCards(ctx context.Context, in *ListCardsRequest, opts ...grpc.CallOption) (*CardsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardsListResponse)
	err := c.cc.Invoke(ctx, KeeperService_ListCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, KeeperService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeeperServiceServer is the server API for KeeperService service.
// All implementations must embed UnimplementedKeeperServiceServer
// for forward compatibility.
type KeeperServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	CreateCredential(context.Context, *CredentialRequest) (*CredentialResponse, error)
	GetCredential(context.Context, *GetRequest) (*CredentialResponse, error)
	UpdateCredential(context.Context, *UpdateCredentialRequest) (*CredentialResponse, error)
	DeleteCredential(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ListCredentials(context.Context, *ListCredentialsRequest) (*CredentialsListResponse, error)
	CreateTextData(context.Context, *TextDataRequest) (*TextDataResponse, error)
	GetTextData(context.Context, *GetRequest) (*TextDataResponse, error)
	UpdateTextData(context.Context, *UpdateTextDataRequest) (*TextDataResponse, error)
	DeleteTextData(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ListTextData(context.Context, *ListTextDataRequest) (*TextDataListResponse, error)
	CreateBinaryData(context.Context, *BinaryDataRequest) (*BinaryDataResponse, error)
	GetBinaryData(context.Context, *GetRequest) (*BinaryDataResponse, error)
	UpdateBinaryData(context.Context, *UpdateBinaryDataRequest) (*BinaryDataResponse, error)
	DeleteBinaryData(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ListBinaryData(context.Context, *ListBinaryDataRequest) (*BinaryDataListResponse, error)
	CreateCard(context.Context, *CardRequest) (*CardResponse, error)
	GetCard(context.Context, *GetRequest) (*CardResponse, error)
	UpdateCard(context.Context, *UpdateCardRequest) (*CardResponse, error)
	DeleteCard(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ListCards(context.Context, *ListCardsRequest) (*CardsListResponse, error)
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	mustEmbedUnimplementedKeeperServiceServer()
}

// UnimplementedKeeperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeeperServiceServer struct{}

func (UnimplementedKeeperServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedKeeperServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedKeeperServiceServer) CreateCredential(context.Context, *CredentialRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCredential not implemented")
}
func (UnimplementedKeeperServiceServer) GetCredential(context.Context, *GetRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredential not implemented")
}
func (UnimplementedKeeperServiceServer) UpdateCredential(context.Context, *UpdateCredentialRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCredential not implemented")
}
func (UnimplementedKeeperServiceServer) DeleteCredential(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedKeeperServiceServer) ListCredentials(context.Context, *ListCredentialsRequest) (*CredentialsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCredentials not implemented")
}
func (UnimplementedKeeperServiceServer) CreateTextData(context.Context, *TextDataRequest) (*TextDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTextData not implemented")
}
func (UnimplementedKeeperServiceServer) GetTextData(context.Context, *GetRequest) (*TextDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTextData not implemented")
}
func (UnimplementedKeeperServiceServer) UpdateTextData(context.Context, *UpdateTextDataRequest) (*TextDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTextData not implemented")
}
func (UnimplementedKeeperServiceServer) DeleteTextData(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTextData not implemented")
}
func (UnimplementedKeeperServiceServer) ListTextData(context.Context, *ListTextDataRequest) (*TextDataListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTextData not implemented")
}
func (UnimplementedKeeperServiceServer) CreateBinaryData(context.Context, *BinaryDataRequest) (*BinaryDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBinaryData not implemented")
}
func (UnimplementedKeeperServiceServer) GetBinaryData(context.Context, *GetRequest) (*BinaryDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBinaryData not implemented")
}
func (UnimplementedKeeperServiceServer) UpdateBinaryData(context.Context, *UpdateBinaryDataRequest) (*BinaryDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBinaryData not implemented")
}
func (UnimplementedKeeperServiceServer) DeleteBinaryData(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBinaryData not implemented")
}
func (UnimplementedKeeperServiceServer) ListBinaryData(context.Context, *ListBinaryDataRequest) (*BinaryDataListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBinaryData not implemented")
}
func (UnimplementedKeeperServiceServer) CreateCard(context.Context, *CardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCard not implemented")
}
func (UnimplementedKeeperServiceServer) GetCard(context.Context, *GetRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedKeeperServiceServer) UpdateCard(context.Context, *UpdateCardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCard not implemented")
}
func (UnimplementedKeeperServiceServer) DeleteCard(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCard not implemented")
}
func (UnimplementedKeeperServiceServer) ListCards(context.Context, *ListCardsRequest) (*CardsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCards not implemented")
}
func (UnimplementedKeeperServiceServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedKeeperServiceServer) mustEmbedUnimplementedKeeperServiceServer() {}
func (UnimplementedKeeperServiceServer) testEmbeddedByValue()                       {}

// UnsafeKeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeeperServiceServer will
// result in compilation errors.
type UnsafeKeeperServiceServer interface {
	mustEmbedUnimplementedKeeperServiceServer()
}

func RegisterKeeperServiceServer(s grpc.ServiceRegistrar, srv KeeperServiceServer) {
	// If the following call panics, it indicates UnimplementedKeeperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeeperService_ServiceDesc, srv)
}

func _KeeperService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_CreateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).CreateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_CreateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).CreateCredential(ctx, req.(*CredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_GetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).GetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_GetCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).GetCredential(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_UpdateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).UpdateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_UpdateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).UpdateCredential(ctx, req.(*UpdateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DeleteCredential(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_ListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).ListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_ListCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).ListCredentials(ctx, req.(*ListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_CreateTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).CreateTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_CreateTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).CreateTextData(ctx, req.(*TextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_GetTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).GetTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_GetTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).GetTextData(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_UpdateTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).UpdateTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_UpdateTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).UpdateTextData(ctx, req.(*UpdateTextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DeleteTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DeleteTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DeleteTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DeleteTextData(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_ListTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).ListTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_ListTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).ListTextData(ctx, req.(*ListTextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_CreateBinaryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinaryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).CreateBinaryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_CreateBinaryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).CreateBinaryData(ctx, req.(*BinaryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_GetBinaryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).GetBinaryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_GetBinaryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).GetBinaryData(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_UpdateBinaryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBinaryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).UpdateBinaryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_UpdateBinaryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).UpdateBinaryData(ctx, req.(*UpdateBinaryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DeleteBinaryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DeleteBinaryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DeleteBinaryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DeleteBinaryData(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_ListBinaryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBinaryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).ListBinaryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_ListBinaryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).ListBinaryData(ctx, req.(*ListBinaryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_CreateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).CreateCard(ctx, req.(*CardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).GetCard(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_UpdateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).UpdateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_UpdateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).UpdateCard(ctx, req.(*UpdateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_DeleteCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).DeleteCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_DeleteCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).DeleteCard(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_ListCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).ListCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_ListCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).ListCards(ctx, req.(*ListCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeeperService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServiceServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeeperService_ServiceDesc is the grpc.ServiceDesc for KeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keeper.KeeperService",
	HandlerType: (*KeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _KeeperService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _KeeperService_Login_Handler,
		},
		{
			MethodName: "CreateCredential",
			Handler:    _KeeperService_CreateCredential_Handler,
		},
		{
			MethodName: "GetCredential",
			Handler:    _KeeperService_GetCredential_Handler,
		},
		{
			MethodName: "UpdateCredential",
			Handler:    _KeeperService_UpdateCredential_Handler,
		},
		{
			MethodName: "DeleteCredential",
			Handler:    _KeeperService_DeleteCredential_Handler,
		},
		{
			MethodName: "ListCredentials",
			Handler:    _KeeperService_ListCredentials_Handler,
		},
		{
			MethodName: "CreateTextData",
			Handler:    _KeeperService_CreateTextData_Handler,
		},
		{
			MethodName: "GetTextData",
			Handler:    _KeeperService_GetTextData_Handler,
		},
		{
			MethodName: "UpdateTextData",
			Handler:    _KeeperService_UpdateTextData_Handler,
		},
		{
			MethodName: "DeleteTextData",
			Handler:    _KeeperService_DeleteTextData_Handler,
		},
		{
			MethodName: "ListTextData",
			Handler:    _KeeperService_ListTextData_Handler,
		},
		{
			MethodName: "CreateBinaryData",
			Handler:    _KeeperService_CreateBinaryData_Handler,
		},
		{
			MethodName: "GetBinaryData",
			Handler:    _KeeperService_GetBinaryData_Handler,
		},
		{
			MethodName: "UpdateBinaryData",
			Handler:    _KeeperService_UpdateBinaryData_Handler,
		},
		{
			MethodName: "DeleteBinaryData",
			Handler:    _KeeperService_DeleteBinaryData_Handler,
		},
		{
			MethodName: "ListBinaryData",
			Handler:    _KeeperService_ListBinaryData_Handler,
		},
		{
			MethodName: "CreateCard",
			Handler:    _KeeperService_CreateCard_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _KeeperService_GetCard_Handler,
		},
		{
			MethodName: "UpdateCard",
			Handler:    _KeeperService_UpdateCard_Handler,
		},
		{
			MethodName: "DeleteCard",
			Handler:    _KeeperService_DeleteCard_Handler,
		},
		{
			MethodName: "ListCards",
			Handler:    _KeeperService_ListCards_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _KeeperService_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/keeper.proto",
}
