// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/keeper.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRequest) Reset() {
	*x = CredentialRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRequest) ProtoMessage() {}

func (x *CredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRequest.ProtoReflect.Descriptor instead.
func (*CredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CredentialRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CredentialRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CredentialRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type UpdateCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Login         string                 `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Meta          string                 `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCredentialRequest) Reset() {
	*x = UpdateCredentialRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredentialRequest) ProtoMessage() {}

func (x *UpdateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredentialRequest.ProtoReflect.Descriptor instead.
func (*UpdateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCredentialRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCredentialRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCredentialRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UpdateCredentialRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateCredentialRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *UpdateCredentialRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Login         string                 `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Meta          string                 `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialResponse) Reset() {
	*x = CredentialResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialResponse) ProtoMessage() {}

func (x *CredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialResponse.ProtoReflect.Descriptor instead.
func (*CredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CredentialResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CredentialResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CredentialResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CredentialResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *CredentialResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CredentialResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CredentialResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CredentialsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*CredentialResponse  `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsListResponse) Reset() {
	*x = CredentialsListResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsListResponse) ProtoMessage() {}

func (x *CredentialsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsListResponse.ProtoReflect.Descriptor instead.
func (*CredentialsListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *CredentialsListResponse) GetCredentials() []*CredentialResponse {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type TextDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDataRequest) Reset() {
	*x = TextDataRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDataRequest) ProtoMessage() {}

func (x *TextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDataRequest.ProtoReflect.Descriptor instead.
func (*TextDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *TextDataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TextDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TextDataRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type UpdateTextDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTextDataRequest) Reset() {
	*x = UpdateTextDataRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextDataRequest) ProtoMessage() {}

func (x *UpdateTextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateTextDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTextDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTextDataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTextDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UpdateTextDataRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *UpdateTextDataRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TextDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDataResponse) Reset() {
	*x = TextDataResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDataResponse) ProtoMessage() {}

func (x *TextDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDataResponse.ProtoReflect.Descriptor instead.
func (*TextDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{10}
}

func (x *TextDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TextDataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TextDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TextDataResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *TextDataResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TextDataResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TextDataResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TextDataListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextData      []*TextDataResponse    `protobuf:"bytes,1,rep,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDataListResponse) Reset() {
	*x = TextDataListResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDataListResponse) ProtoMessage() {}

func (x *TextDataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDataListResponse.ProtoReflect.Descriptor instead.
func (*TextDataListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{11}
}

func (x *TextDataListResponse) GetTextData() []*TextDataResponse {
	if x != nil {
		return x.TextData
	}
	return nil
}

type BinaryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryDataRequest) Reset() {
	*x = BinaryDataRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryDataRequest) ProtoMessage() {}

func (x *BinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryDataRequest.ProtoReflect.Descriptor instead.
func (*BinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{12}
}

func (x *BinaryDataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BinaryDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BinaryDataRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type UpdateBinaryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBinaryDataRequest) Reset() {
	*x = UpdateBinaryDataRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBinaryDataRequest) ProtoMessage() {}

func (x *UpdateBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateBinaryDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBinaryDataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBinaryDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateBinaryDataRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *UpdateBinaryDataRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BinaryDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryDataResponse) Reset() {
	*x = BinaryDataResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryDataResponse) ProtoMessage() {}

func (x *BinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryDataResponse.ProtoReflect.Descriptor instead.
func (*BinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{14}
}

func (x *BinaryDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BinaryDataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BinaryDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BinaryDataResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *BinaryDataResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BinaryDataResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BinaryDataResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BinaryDataListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BinaryData    []*BinaryDataResponse  `protobuf:"bytes,1,rep,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryDataListResponse) Reset() {
	*x = BinaryDataListResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryDataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryDataListResponse) ProtoMessage() {}

func (x *BinaryDataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryDataListResponse.ProtoReflect.Descriptor instead.
func (*BinaryDataListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{15}
}

func (x *BinaryDataListResponse) GetBinaryData() []*BinaryDataResponse {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

type CardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardHolder    string                 `protobuf:"bytes,3,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	Expiry        string                 `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Cvv           string                 `protobuf:"bytes,5,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Meta          string                 `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{16}
}

func (x *CardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardRequest) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

func (x *CardRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *CardRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardHolder    string                 `protobuf:"bytes,4,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	Expiry        string                 `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Cvv           string                 `protobuf:"bytes,6,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Meta          string                 `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateCardRequest) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

func (x *UpdateCardRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *UpdateCardRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *UpdateCardRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *UpdateCardRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardHolder    string                 `protobuf:"bytes,4,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	Expiry        string                 `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Cvv           string                 `protobuf:"bytes,6,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Meta          string                 `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{18}
}

func (x *CardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardResponse) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

func (x *CardResponse) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *CardResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *CardResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CardResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CardResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CardsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*CardResponse        `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardsListResponse) Reset() {
	*x = CardsListResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardsListResponse) ProtoMessage() {}

func (x *CardsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardsListResponse.ProtoReflect.Descriptor instead.
func (*CardsListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{19}
}

func (x *CardsListResponse) GetCards() []*CardResponse {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{20}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSync      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_proto_keeper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{22}
}

func (x *SyncRequest) GetLastSync() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSync
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*CredentialResponse  `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	TextData      []*TextDataResponse    `protobuf:"bytes,2,rep,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	BinaryData    []*BinaryDataResponse  `protobuf:"bytes,3,rep,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty"`
	Cards         []*CardResponse        `protobuf:"bytes,4,rep,name=cards,proto3" json:"cards,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_proto_keeper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeper_proto_rawDescGZIP(), []int{23}
}

func (x *SyncResponse) GetCredentials() []*CredentialResponse {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *SyncResponse) GetTextData() []*TextDataResponse {
	if x != nil {
		return x.TextData
	}
	return nil
}

func (x *SyncResponse) GetBinaryData() []*BinaryDataResponse {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

func (x *SyncResponse) GetCards() []*CardResponse {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *SyncResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_api_proto_keeper_proto protoreflect.FileDescriptor

const file_api_proto_keeper_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/keeper.proto\x12\x06keeper\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"o\n" +
	"\x11CredentialRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\"\x9f\x01\n" +
	"\x17UpdateCredentialRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05login\x18\x03 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04meta\x18\x05 \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\"\x90\x02\n" +
	"\x12CredentialResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05login\x18\x03 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04meta\x18\x05 \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"W\n" +
	"\x17CredentialsListResponse\x12<\n" +
	"\vcredentials\x18\x01 \x03(\v2\x1a.keeper.CredentialResponseR\vcredentials\"O\n" +
	"\x0fTextDataRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\"\x7f\n" +
	"\x15UpdateTextDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"\xf0\x01\n" +
	"\x10TextDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"M\n" +
	"\x14TextDataListResponse\x125\n" +
	"\ttext_data\x18\x01 \x03(\v2\x18.keeper.TextDataResponseR\btextData\"Q\n" +
	"\x11BinaryDataRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\"\x81\x01\n" +
	"\x17UpdateBinaryDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"\xf2\x01\n" +
	"\x12BinaryDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"U\n" +
	"\x16BinaryDataListResponse\x12;\n" +
	"\vbinary_data\x18\x01 \x03(\v2\x1a.keeper.BinaryDataResponseR\n" +
	"binaryData\"\xa3\x01\n" +
	"\vCardRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12\x1f\n" +
	"\vcard_holder\x18\x03 \x01(\tR\n" +
	"cardHolder\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x12\n" +
	"\x04meta\x18\x06 \x01(\tR\x04meta\"\xd3\x01\n" +
	"\x11UpdateCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1f\n" +
	"\vcard_holder\x18\x04 \x01(\tR\n" +
	"cardHolder\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x06 \x01(\tR\x03cvv\x12\x12\n" +
	"\x04meta\x18\a \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\"\xc4\x02\n" +
	"\fCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1f\n" +
	"\vcard_holder\x18\x04 \x01(\tR\n" +
	"cardHolder\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x06 \x01(\tR\x03cvv\x12\x12\n" +
	"\x04meta\x18\a \x01(\tR\x04meta\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"?\n" +
	"\x11CardsListResponse\x12*\n" +
	"\x05cards\x18\x01 \x03(\v2\x14.keeper.CardResponseR\x05cards\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\vSyncRequest\x127\n" +
	"\tlast_sync\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\blastSync\"\xa9\x02\n" +
	"\fSyncResponse\x12<\n" +
	"\vcredentials\x18\x01 \x03(\v2\x1a.keeper.CredentialResponseR\vcredentials\x125\n" +
	"\ttext_data\x18\x02 \x03(\v2\x18.keeper.TextDataResponseR\btextData\x12;\n" +
	"\vbinary_data\x18\x03 \x03(\v2\x1a.keeper.BinaryDataResponseR\n" +
	"binaryData\x12*\n" +
	"\x05cards\x18\x04 \x03(\v2\x14.keeper.CardResponseR\x05cards\x12;\n" +
	"\vserver_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime2\x8b\f\n" +
	"\rKeeperService\x12=\n" +
	"\bRegister\x12\x17.keeper.RegisterRequest\x1a\x18.keeper.RegisterResponse\x124\n" +
	"\x05Login\x12\x14.keeper.LoginRequest\x1a\x15.keeper.LoginResponse\x12I\n" +
	"\x10CreateCredential\x12\x19.keeper.CredentialRequest\x1a\x1a.keeper.CredentialResponse\x12?\n" +
	"\rGetCredential\x12\x12.keeper.GetRequest\x1a\x1a.keeper.CredentialResponse\x12O\n" +
	"\x10UpdateCredential\x12\x1f.keeper.UpdateCredentialRequest\x1a\x1a.keeper.CredentialResponse\x12A\n" +
	"\x10DeleteCredential\x12\x15.keeper.DeleteRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0fListCredentials\x12\x16.google.protobuf.Empty\x1a\x1f.keeper.CredentialsListResponse\x12C\n" +
	"\x0eCreateTextData\x12\x17.keeper.TextDataRequest\x1a\x18.keeper.TextDataResponse\x12;\n" +
	"\vGetTextData\x12\x12.keeper.GetRequest\x1a\x18.keeper.TextDataResponse\x12I\n" +
	"\x0eUpdateTextData\x12\x1d.keeper.UpdateTextDataRequest\x1a\x18.keeper.TextDataResponse\x12?\n" +
	"\x0eDeleteTextData\x12\x15.keeper.DeleteRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fListTextData\x12\x16.google.protobuf.Empty\x1a\x1c.keeper.TextDataListResponse\x12I\n" +
	"\x10CreateBinaryData\x12\x19.keeper.BinaryDataRequest\x1a\x1a.keeper.BinaryDataResponse\x12?\n" +
	"\rGetBinaryData\x12\x12.keeper.GetRequest\x1a\x1a.keeper.BinaryDataResponse\x12O\n" +
	"\x10UpdateBinaryData\x12\x1f.keeper.UpdateBinaryDataRequest\x1a\x1a.keeper.BinaryDataResponse\x12A\n" +
	"\x10DeleteBinaryData\x12\x15.keeper.DeleteRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x0eListBinaryData\x12\x16.google.protobuf.Empty\x1a\x1e.keeper.BinaryDataListResponse\x127\n" +
	"\n" +
	"CreateCard\x12\x13.keeper.CardRequest\x1a\x14.keeper.CardResponse\x123\n" +
	"\aGetCard\x12\x12.keeper.GetRequest\x1a\x14.keeper.CardResponse\x12=\n" +
	"\n" +
	"UpdateCard\x12\x19.keeper.UpdateCardRequest\x1a\x14.keeper.CardResponse\x12;\n" +
	"\n" +
	"DeleteCard\x12\x15.keeper.DeleteRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tListCards\x12\x16.google.protobuf.Empty\x1a\x19.keeper.CardsListResponse\x121\n" +
	"\x04Sync\x12\x13.keeper.SyncRequest\x1a\x14.keeper.SyncResponseB,Z*github.com/a-blokhin/goph-keeper/api/protob\x06proto3"

var (
	file_api_proto_keeper_proto_rawDescOnce sync.Once
	file_api_proto_keeper_proto_rawDescData []byte
)

func file_api_proto_keeper_proto_rawDescGZIP() []byte {
	file_api_proto_keeper_proto_rawDescOnce.Do(func() {
		file_api_proto_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_keeper_proto_rawDesc), len(file_api_proto_keeper_proto_rawDesc)))
	})
	return file_api_proto_keeper_proto_rawDescData
}

var file_api_proto_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_keeper_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: keeper.RegisterRequest
	(*RegisterResponse)(nil),        // 1: keeper.RegisterResponse
	(*LoginRequest)(nil),            // 2: keeper.LoginRequest
	(*LoginResponse)(nil),           // 3: keeper.LoginResponse
	(*CredentialRequest)(nil),       // 4: keeper.CredentialRequest
	(*UpdateCredentialRequest)(nil), // 5: keeper.UpdateCredentialRequest
	(*CredentialResponse)(nil),      // 6: keeper.CredentialResponse
	(*CredentialsListResponse)(nil), // 7: keeper.CredentialsListResponse
	(*TextDataRequest)(nil),         // 8: keeper.TextDataRequest
	(*UpdateTextDataRequest)(nil),   // 9: keeper.UpdateTextDataRequest
	(*TextDataResponse)(nil),        // 10: keeper.TextDataResponse
	(*TextDataListResponse)(nil),    // 11: keeper.TextDataListResponse
	(*BinaryDataRequest)(nil),       // 12: keeper.BinaryDataRequest
	(*UpdateBinaryDataRequest)(nil), // 13: keeper.UpdateBinaryDataRequest
	(*BinaryDataResponse)(nil),      // 14: keeper.BinaryDataResponse
	(*BinaryDataListResponse)(nil),  // 15: keeper.BinaryDataListResponse
	(*CardRequest)(nil),             // 16: keeper.CardRequest
	(*UpdateCardRequest)(nil),       // 17: keeper.UpdateCardRequest
	(*CardResponse)(nil),            // 18: keeper.CardResponse
	(*CardsListResponse)(nil),       // 19: keeper.CardsListResponse
	(*GetRequest)(nil),              // 20: keeper.GetRequest
	(*DeleteRequest)(nil),           // 21: keeper.DeleteRequest
	(*SyncRequest)(nil),             // 22: keeper.SyncRequest
	(*SyncResponse)(nil),            // 23: keeper.SyncResponse
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 25: google.protobuf.Empty
}
var file_api_proto_keeper_proto_depIdxs = []int32{
	24, // 0: keeper.CredentialResponse.created_at:type_name -> google.protobuf.Timestamp
	24, // 1: keeper.CredentialResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: keeper.CredentialsListResponse.credentials:type_name -> keeper.CredentialResponse
	24, // 3: keeper.TextDataResponse.created_at:type_name -> google.protobuf.Timestamp
	24, // 4: keeper.TextDataResponse.updated_at:type_name -> google.protobuf.Timestamp
	10, // 5: keeper.TextDataListResponse.text_data:type_name -> keeper.TextDataResponse
	24, // 6: keeper.BinaryDataResponse.created_at:type_name -> google.protobuf.Timestamp
	24, // 7: keeper.BinaryDataResponse.updated_at:type_name -> google.protobuf.Timestamp
	14, // 8: keeper.BinaryDataListResponse.binary_data:type_name -> keeper.BinaryDataResponse
	24, // 9: keeper.CardResponse.created_at:type_name -> google.protobuf.Timestamp
	24, // 10: keeper.CardResponse.updated_at:type_name -> google.protobuf.Timestamp
	18, // 11: keeper.CardsListResponse.cards:type_name -> keeper.CardResponse
	24, // 12: keeper.SyncRequest.last_sync:type_name -> google.protobuf.Timestamp
	6,  // 13: keeper.SyncResponse.credentials:type_name -> keeper.CredentialResponse
	10, // 14: keeper.SyncResponse.text_data:type_name -> keeper.TextDataResponse
	14, // 15: keeper.SyncResponse.binary_data:type_name -> keeper.BinaryDataResponse
	18, // 16: keeper.SyncResponse.cards:type_name -> keeper.CardResponse
	24, // 17: keeper.SyncResponse.server_time:type_name -> google.protobuf.Timestamp
	0,  // 18: keeper.KeeperService.Register:input_type -> keeper.RegisterRequest
	2,  // 19: keeper.KeeperService.Login:input_type -> keeper.LoginRequest
	4,  // 20: keeper.KeeperService.CreateCredential:input_type -> keeper.CredentialRequest
	20, // 21: keeper.KeeperService.GetCredential:input_type -> keeper.GetRequest
	5,  // 22: keeper.KeeperService.UpdateCredential:input_type -> keeper.UpdateCredentialRequest
	21, // 23: keeper.KeeperService.DeleteCredential:input_type -> keeper.DeleteRequest
	25, // 24: keeper.KeeperService.ListCredentials:input_type -> google.protobuf.Empty
	8,  // 25: keeper.KeeperService.CreateTextData:input_type -> keeper.TextDataRequest
	20, // 26: keeper.KeeperService.GetTextData:input_type -> keeper.GetRequest
	9,  // 27: keeper.KeeperService.UpdateTextData:input_type -> keeper.UpdateTextDataRequest
	21, // 28: keeper.KeeperService.DeleteTextData:input_type -> keeper.DeleteRequest
	25, // 29: keeper.KeeperService.ListTextData:input_type -> google.protobuf.Empty
	12, // 30: keeper.KeeperService.CreateBinaryData:input_type -> keeper.BinaryDataRequest
	20, // 31: keeper.KeeperService.GetBinaryData:input_type -> keeper.GetRequest
	13, // 32: keeper.KeeperService.UpdateBinaryData:input_type -> keeper.UpdateBinaryDataRequest
	21, // 33: keeper.KeeperService.DeleteBinaryData:input_type -> keeper.DeleteRequest
	25, // 34: keeper.KeeperService.ListBinaryData:input_type -> google.protobuf.Empty
	16, // 35: keeper.KeeperService.CreateCard:input_type -> keeper.CardRequest
	20, // 36: keeper.KeeperService.GetCard:input_type -> keeper.GetRequest
	17, // 37: keeper.KeeperService.UpdateCard:input_type -> keeper.UpdateCardRequest
	21, // 38: keeper.KeeperService.DeleteCard:input_type -> keeper.DeleteRequest
	25, // 39: keeper.KeeperService.ListCards:input_type -> google.protobuf.Empty
	22, // 40: keeper.KeeperService.Sync:input_type -> keeper.SyncRequest
	1,  // 41: keeper.KeeperService.Register:output_type -> keeper.RegisterResponse
	3,  // 42: keeper.KeeperService.Login:output_type -> keeper.LoginResponse
	6,  // 43: keeper.KeeperService.CreateCredential:output_type -> keeper.CredentialResponse
	6,  // 44: keeper.KeeperService.GetCredential:output_type -> keeper.CredentialResponse
	6,  // 45: keeper.KeeperService.UpdateCredential:output_type -> keeper.CredentialResponse
	25, // 46: keeper.KeeperService.DeleteCredential:output_type -> google.protobuf.Empty
	7,  // 47: keeper.KeeperService.ListCredentials:output_type -> keeper.CredentialsListResponse
	10, // 48: keeper.KeeperService.CreateTextData:output_type -> keeper.TextDataResponse
	10, // 49: keeper.KeeperService.GetTextData:output_type -> keeper.TextDataResponse
	10, // 50: keeper.KeeperService.UpdateTextData:output_type -> keeper.TextDataResponse
	25, // 51: keeper.KeeperService.DeleteTextData:output_type -> google.protobuf.Empty
	11, // 52: keeper.KeeperService.ListTextData:output_type -> keeper.TextDataListResponse
	14, // 53: keeper.KeeperService.CreateBinaryData:output_type -> keeper.BinaryDataResponse
	14, // 54: keeper.KeeperService.GetBinaryData:output_type -> keeper.BinaryDataResponse
	14, // 55: keeper.KeeperService.UpdateBinaryData:output_type -> keeper.BinaryDataResponse
	25, // 56: keeper.KeeperService.DeleteBinaryData:output_type -> google.protobuf.Empty
	15, // 57: keeper.KeeperService.ListBinaryData:output_type -> keeper.BinaryDataListResponse
	18, // 58: keeper.KeeperService.CreateCard:output_type -> keeper.CardResponse
	18, // 59: keeper.KeeperService.GetCard:output_type -> keeper.CardResponse
	18, // 60: keeper.KeeperService.UpdateCard:output_type -> keeper.CardResponse
	25, // 61: keeper.KeeperService.DeleteCard:output_type -> google.protobuf.Empty
	19, // 62: keeper.KeeperService.ListCards:output_type -> keeper.CardsListResponse
	23, // 63: keeper.KeeperService.Sync:output_type -> keeper.SyncResponse
	41, // [41:64] is the sub-list for method output_type
	18, // [18:41] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_keeper_proto_init() }
func file_api_proto_keeper_proto_init() {
	if File_api_proto_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_keeper_proto_rawDesc), len(file_api_proto_keeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_keeper_proto_goTypes,
		DependencyIndexes: file_api_proto_keeper_proto_depIdxs,
		MessageInfos:      file_api_proto_keeper_proto_msgTypes,
	}.Build()
	File_api_proto_keeper_proto = out.File
	file_api_proto_keeper_proto_goTypes = nil
	file_api_proto_keeper_proto_depIdxs = nil
}
