// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteCardUsecase is an autogenerated mock type for the DeleteCardUsecase type
type DeleteCardUsecase struct {
	mock.Mock
}

type DeleteCardUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteCardUsecase) EXPECT() *DeleteCardUsecase_Expecter {
	return &DeleteCardUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, cardID
func (_m *DeleteCardUsecase) Execute(ctx context.Context, userID string, cardID string) error {
	ret := _m.Called(ctx, userID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, cardID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCardUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteCardUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - cardID string
func (_e *DeleteCardUsecase_Expecter) Execute(ctx interface{}, userID interface{}, cardID interface{}) *DeleteCardUsecase_Execute_Call {
	return &DeleteCardUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, cardID)}
}

func (_c *DeleteCardUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, cardID string)) *DeleteCardUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DeleteCardUsecase_Execute_Call) Return(_a0 error) *DeleteCardUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteCardUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, string) error) *DeleteCardUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteCardUsecase creates a new instance of DeleteCardUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteCardUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteCardUsecase {
	mock := &DeleteCardUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
