// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/a-blokhin/goph-keeper/internal/model"
)

// GetCredentialUsecase is an autogenerated mock type for the GetCredentialUsecase type
type GetCredentialUsecase struct {
	mock.Mock
}

type GetCredentialUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetCredentialUsecase) EXPECT() *GetCredentialUsecase_Expecter {
	return &GetCredentialUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, id
func (_m *GetCredentialUsecase) Execute(ctx context.Context, userID string, id string) (*model.Credential, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *model.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Credential, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Credential); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCredentialUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetCredentialUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *GetCredentialUsecase_Expecter) Execute(ctx interface{}, userID interface{}, id interface{}) *GetCredentialUsecase_Execute_Call {
	return &GetCredentialUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, id)}
}

func (_c *GetCredentialUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, id string)) *GetCredentialUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *GetCredentialUsecase_Execute_Call) Return(_a0 *model.Credential, _a1 error) *GetCredentialUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetCredentialUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, string) (*model.Credential, error)) *GetCredentialUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetCredentialUsecase creates a new instance of GetCredentialUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetCredentialUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetCredentialUsecase {
	mock := &GetCredentialUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
