// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteCredentialUsecase is an autogenerated mock type for the DeleteCredentialUsecase type
type DeleteCredentialUsecase struct {
	mock.Mock
}

type DeleteCredentialUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteCredentialUsecase) EXPECT() *DeleteCredentialUsecase_Expecter {
	return &DeleteCredentialUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, credentialID
func (_m *DeleteCredentialUsecase) Execute(ctx context.Context, userID string, credentialID string) error {
	ret := _m.Called(ctx, userID, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, credentialID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCredentialUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteCredentialUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - credentialID string
func (_e *DeleteCredentialUsecase_Expecter) Execute(ctx interface{}, userID interface{}, credentialID interface{}) *DeleteCredentialUsecase_Execute_Call {
	return &DeleteCredentialUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, credentialID)}
}

func (_c *DeleteCredentialUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, credentialID string)) *DeleteCredentialUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DeleteCredentialUsecase_Execute_Call) Return(_a0 error) *DeleteCredentialUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteCredentialUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, string) error) *DeleteCredentialUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteCredentialUsecase creates a new instance of DeleteCredentialUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteCredentialUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteCredentialUsecase {
	mock := &DeleteCredentialUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
