CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

GRANT ALL PRIVILEGES ON SCHEMA public TO gophkeeper;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gophkeeper;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO gophkeeper;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO gophkeeper;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO gophkeeper;