// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/a-blokhin/goph-keeper/internal/model"
)

// LoginUsecase is an autogenerated mock type for the LoginUsecase type
type LoginUsecase struct {
	mock.Mock
}

type LoginUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginUsecase) EXPECT() *LoginUsecase_Expecter {
	return &LoginUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, email, password
func (_m *LoginUsecase) Execute(ctx context.Context, email string, password string) (*model.User, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *model.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LoginUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type LoginUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *LoginUsecase_Expecter) Execute(ctx interface{}, email interface{}, password interface{}) *LoginUsecase_Execute_Call {
	return &LoginUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, email, password)}
}

func (_c *LoginUsecase_Execute_Call) Run(run func(ctx context.Context, email string, password string)) *LoginUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LoginUsecase_Execute_Call) Return(_a0 *model.User, _a1 string, _a2 error) *LoginUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *LoginUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, string) (*model.User, string, error)) *LoginUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoginUsecase creates a new instance of LoginUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginUsecase {
	mock := &LoginUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
