// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/a-blokhin/goph-keeper/internal/model"
)

// CreateTextDataUsecase is an autogenerated mock type for the CreateTextDataUsecase type
type CreateTextDataUsecase struct {
	mock.Mock
}

type CreateTextDataUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateTextDataUsecase) EXPECT() *CreateTextDataUsecase_Expecter {
	return &CreateTextDataUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, textData
func (_m *CreateTextDataUsecase) Execute(ctx context.Context, userID string, textData *model.TextData) error {
	ret := _m.Called(ctx, userID, textData)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.TextData) error); ok {
		r0 = rf(ctx, userID, textData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTextDataUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateTextDataUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - textData *model.TextData
func (_e *CreateTextDataUsecase_Expecter) Execute(ctx interface{}, userID interface{}, textData interface{}) *CreateTextDataUsecase_Execute_Call {
	return &CreateTextDataUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, textData)}
}

func (_c *CreateTextDataUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, textData *model.TextData)) *CreateTextDataUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.TextData))
	})
	return _c
}

func (_c *CreateTextDataUsecase_Execute_Call) Return(_a0 error) *CreateTextDataUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreateTextDataUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, *model.TextData) error) *CreateTextDataUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateTextDataUsecase creates a new instance of CreateTextDataUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateTextDataUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateTextDataUsecase {
	mock := &CreateTextDataUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
