// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/a-blokhin/goph-keeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UpdateBinaryDataUsecase is an autogenerated mock type for the UpdateBinaryDataUsecase type
type UpdateBinaryDataUsecase struct {
	mock.Mock
}

type UpdateBinaryDataUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateBinaryDataUsecase) EXPECT() *UpdateBinaryDataUsecase_Expecter {
	return &UpdateBinaryDataUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, binaryData
func (_m *UpdateBinaryDataUsecase) Execute(ctx context.Context, userID string, binaryData *model.BinaryData) error {
	ret := _m.Called(ctx, userID, binaryData)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.BinaryData) error); ok {
		r0 = rf(ctx, userID, binaryData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBinaryDataUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateBinaryDataUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - binaryData *model.BinaryData
func (_e *UpdateBinaryDataUsecase_Expecter) Execute(ctx interface{}, userID interface{}, binaryData interface{}) *UpdateBinaryDataUsecase_Execute_Call {
	return &UpdateBinaryDataUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, binaryData)}
}

func (_c *UpdateBinaryDataUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, binaryData *model.BinaryData)) *UpdateBinaryDataUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.BinaryData))
	})
	return _c
}

func (_c *UpdateBinaryDataUsecase_Execute_Call) Return(_a0 error) *UpdateBinaryDataUsecase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UpdateBinaryDataUsecase_Execute_Call) RunAndReturn(run func(context.Context, string, *model.BinaryData) error) *UpdateBinaryDataUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdateBinaryDataUsecase creates a new instance of UpdateBinaryDataUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateBinaryDataUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateBinaryDataUsecase {
	mock := &UpdateBinaryDataUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
