// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/a-blokhin/goph-keeper/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// EncryptionService is an autogenerated mock type for the EncryptionService type
type EncryptionService struct {
	mock.Mock
}

type EncryptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *EncryptionService) EXPECT() *EncryptionService_Expecter {
	return &EncryptionService_Expecter{mock: &_m.Mock}
}

// DecryptBinary provides a mock function with given fields: encryptedData
func (_m *EncryptionService) DecryptBinary(encryptedData []byte) ([]byte, error) {
	ret := _m.Called(encryptedData)

	if len(ret) == 0 {
		panic("no return value specified for DecryptBinary")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(encryptedData)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(encryptedData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(encryptedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptionService_DecryptBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptBinary'
type EncryptionService_DecryptBinary_Call struct {
	*mock.Call
}

// DecryptBinary is a helper method to define mock.On call
//   - encryptedData []byte
func (_e *EncryptionService_Expecter) DecryptBinary(encryptedData interface{}) *EncryptionService_DecryptBinary_Call {
	return &EncryptionService_DecryptBinary_Call{Call: _e.mock.On("DecryptBinary", encryptedData)}
}

func (_c *EncryptionService_DecryptBinary_Call) Run(run func(encryptedData []byte)) *EncryptionService_DecryptBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *EncryptionService_DecryptBinary_Call) Return(_a0 []byte, _a1 error) *EncryptionService_DecryptBinary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EncryptionService_DecryptBinary_Call) RunAndReturn(run func([]byte) ([]byte, error)) *EncryptionService_DecryptBinary_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptBinaryData provides a mock function with given fields: binaryData
func (_m *EncryptionService) DecryptBinaryData(binaryData *model.BinaryData) error {
	ret := _m.Called(binaryData)

	if len(ret) == 0 {
		panic("no return value specified for DecryptBinaryData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.BinaryData) error); ok {
		r0 = rf(binaryData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_DecryptBinaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptBinaryData'
type EncryptionService_DecryptBinaryData_Call struct {
	*mock.Call
}

// DecryptBinaryData is a helper method to define mock.On call
//   - binaryData *model.BinaryData
func (_e *EncryptionService_Expecter) DecryptBinaryData(binaryData interface{}) *EncryptionService_DecryptBinaryData_Call {
	return &EncryptionService_DecryptBinaryData_Call{Call: _e.mock.On("DecryptBinaryData", binaryData)}
}

func (_c *EncryptionService_DecryptBinaryData_Call) Run(run func(binaryData *model.BinaryData)) *EncryptionService_DecryptBinaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.BinaryData))
	})
	return _c
}

func (_c *EncryptionService_DecryptBinaryData_Call) Return(_a0 error) *EncryptionService_DecryptBinaryData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_DecryptBinaryData_Call) RunAndReturn(run func(*model.BinaryData) error) *EncryptionService_DecryptBinaryData_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptCard provides a mock function with given fields: encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV
func (_m *EncryptionService) DecryptCard(encryptedCardNumber string, encryptedCardHolder string, encryptedExpiry string, encryptedCVV string) (string, string, string, string, error) {
	ret := _m.Called(encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV)

	if len(ret) == 0 {
		panic("no return value specified for DecryptCard")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 string
	var r4 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (string, string, string, string, error)); ok {
		return rf(encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) string); ok {
		r1 = rf(encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string) string); ok {
		r2 = rf(encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(string, string, string, string) string); ok {
		r3 = rf(encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV)
	} else {
		r3 = ret.Get(3).(string)
	}

	if rf, ok := ret.Get(4).(func(string, string, string, string) error); ok {
		r4 = rf(encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// EncryptionService_DecryptCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptCard'
type EncryptionService_DecryptCard_Call struct {
	*mock.Call
}

// DecryptCard is a helper method to define mock.On call
//   - encryptedCardNumber string
//   - encryptedCardHolder string
//   - encryptedExpiry string
//   - encryptedCVV string
func (_e *EncryptionService_Expecter) DecryptCard(encryptedCardNumber interface{}, encryptedCardHolder interface{}, encryptedExpiry interface{}, encryptedCVV interface{}) *EncryptionService_DecryptCard_Call {
	return &EncryptionService_DecryptCard_Call{Call: _e.mock.On("DecryptCard", encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV)}
}

func (_c *EncryptionService_DecryptCard_Call) Run(run func(encryptedCardNumber string, encryptedCardHolder string, encryptedExpiry string, encryptedCVV string)) *EncryptionService_DecryptCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *EncryptionService_DecryptCard_Call) Return(cardNumber string, cardHolder string, expiry string, cvv string, err error) *EncryptionService_DecryptCard_Call {
	_c.Call.Return(cardNumber, cardHolder, expiry, cvv, err)
	return _c
}

func (_c *EncryptionService_DecryptCard_Call) RunAndReturn(run func(string, string, string, string) (string, string, string, string, error)) *EncryptionService_DecryptCard_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptCardData provides a mock function with given fields: card
func (_m *EncryptionService) DecryptCardData(card *model.Card) error {
	ret := _m.Called(card)

	if len(ret) == 0 {
		panic("no return value specified for DecryptCardData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Card) error); ok {
		r0 = rf(card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_DecryptCardData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptCardData'
type EncryptionService_DecryptCardData_Call struct {
	*mock.Call
}

// DecryptCardData is a helper method to define mock.On call
//   - card *model.Card
func (_e *EncryptionService_Expecter) DecryptCardData(card interface{}) *EncryptionService_DecryptCardData_Call {
	return &EncryptionService_DecryptCardData_Call{Call: _e.mock.On("DecryptCardData", card)}
}

func (_c *EncryptionService_DecryptCardData_Call) Run(run func(card *model.Card)) *EncryptionService_DecryptCardData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Card))
	})
	return _c
}

func (_c *EncryptionService_DecryptCardData_Call) Return(_a0 error) *EncryptionService_DecryptCardData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_DecryptCardData_Call) RunAndReturn(run func(*model.Card) error) *EncryptionService_DecryptCardData_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptCredential provides a mock function with given fields: credential
func (_m *EncryptionService) DecryptCredential(credential *model.Credential) error {
	ret := _m.Called(credential)

	if len(ret) == 0 {
		panic("no return value specified for DecryptCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Credential) error); ok {
		r0 = rf(credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_DecryptCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptCredential'
type EncryptionService_DecryptCredential_Call struct {
	*mock.Call
}

// DecryptCredential is a helper method to define mock.On call
//   - credential *model.Credential
func (_e *EncryptionService_Expecter) DecryptCredential(credential interface{}) *EncryptionService_DecryptCredential_Call {
	return &EncryptionService_DecryptCredential_Call{Call: _e.mock.On("DecryptCredential", credential)}
}

func (_c *EncryptionService_DecryptCredential_Call) Run(run func(credential *model.Credential)) *EncryptionService_DecryptCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Credential))
	})
	return _c
}

func (_c *EncryptionService_DecryptCredential_Call) Return(_a0 error) *EncryptionService_DecryptCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_DecryptCredential_Call) RunAndReturn(run func(*model.Credential) error) *EncryptionService_DecryptCredential_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptPassword provides a mock function with given fields: encryptedPassword
func (_m *EncryptionService) DecryptPassword(encryptedPassword string) (string, error) {
	ret := _m.Called(encryptedPassword)

	if len(ret) == 0 {
		panic("no return value specified for DecryptPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(encryptedPassword)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(encryptedPassword)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(encryptedPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptionService_DecryptPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptPassword'
type EncryptionService_DecryptPassword_Call struct {
	*mock.Call
}

// DecryptPassword is a helper method to define mock.On call
//   - encryptedPassword string
func (_e *EncryptionService_Expecter) DecryptPassword(encryptedPassword interface{}) *EncryptionService_DecryptPassword_Call {
	return &EncryptionService_DecryptPassword_Call{Call: _e.mock.On("DecryptPassword", encryptedPassword)}
}

func (_c *EncryptionService_DecryptPassword_Call) Run(run func(encryptedPassword string)) *EncryptionService_DecryptPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EncryptionService_DecryptPassword_Call) Return(_a0 string, _a1 error) *EncryptionService_DecryptPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EncryptionService_DecryptPassword_Call) RunAndReturn(run func(string) (string, error)) *EncryptionService_DecryptPassword_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptText provides a mock function with given fields: encryptedText
func (_m *EncryptionService) DecryptText(encryptedText string) (string, error) {
	ret := _m.Called(encryptedText)

	if len(ret) == 0 {
		panic("no return value specified for DecryptText")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(encryptedText)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(encryptedText)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(encryptedText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptionService_DecryptText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptText'
type EncryptionService_DecryptText_Call struct {
	*mock.Call
}

// DecryptText is a helper method to define mock.On call
//   - encryptedText string
func (_e *EncryptionService_Expecter) DecryptText(encryptedText interface{}) *EncryptionService_DecryptText_Call {
	return &EncryptionService_DecryptText_Call{Call: _e.mock.On("DecryptText", encryptedText)}
}

func (_c *EncryptionService_DecryptText_Call) Run(run func(encryptedText string)) *EncryptionService_DecryptText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EncryptionService_DecryptText_Call) Return(_a0 string, _a1 error) *EncryptionService_DecryptText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EncryptionService_DecryptText_Call) RunAndReturn(run func(string) (string, error)) *EncryptionService_DecryptText_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptTextData provides a mock function with given fields: textData
func (_m *EncryptionService) DecryptTextData(textData *model.TextData) error {
	ret := _m.Called(textData)

	if len(ret) == 0 {
		panic("no return value specified for DecryptTextData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.TextData) error); ok {
		r0 = rf(textData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_DecryptTextData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptTextData'
type EncryptionService_DecryptTextData_Call struct {
	*mock.Call
}

// DecryptTextData is a helper method to define mock.On call
//   - textData *model.TextData
func (_e *EncryptionService_Expecter) DecryptTextData(textData interface{}) *EncryptionService_DecryptTextData_Call {
	return &EncryptionService_DecryptTextData_Call{Call: _e.mock.On("DecryptTextData", textData)}
}

func (_c *EncryptionService_DecryptTextData_Call) Run(run func(textData *model.TextData)) *EncryptionService_DecryptTextData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TextData))
	})
	return _c
}

func (_c *EncryptionService_DecryptTextData_Call) Return(_a0 error) *EncryptionService_DecryptTextData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_DecryptTextData_Call) RunAndReturn(run func(*model.TextData) error) *EncryptionService_DecryptTextData_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptBinary provides a mock function with given fields: data
func (_m *EncryptionService) EncryptBinary(data []byte) ([]byte, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for EncryptBinary")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptionService_EncryptBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptBinary'
type EncryptionService_EncryptBinary_Call struct {
	*mock.Call
}

// EncryptBinary is a helper method to define mock.On call
//   - data []byte
func (_e *EncryptionService_Expecter) EncryptBinary(data interface{}) *EncryptionService_EncryptBinary_Call {
	return &EncryptionService_EncryptBinary_Call{Call: _e.mock.On("EncryptBinary", data)}
}

func (_c *EncryptionService_EncryptBinary_Call) Run(run func(data []byte)) *EncryptionService_EncryptBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *EncryptionService_EncryptBinary_Call) Return(_a0 []byte, _a1 error) *EncryptionService_EncryptBinary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EncryptionService_EncryptBinary_Call) RunAndReturn(run func([]byte) ([]byte, error)) *EncryptionService_EncryptBinary_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptBinaryData provides a mock function with given fields: binaryData
func (_m *EncryptionService) EncryptBinaryData(binaryData *model.BinaryData) error {
	ret := _m.Called(binaryData)

	if len(ret) == 0 {
		panic("no return value specified for EncryptBinaryData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.BinaryData) error); ok {
		r0 = rf(binaryData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_EncryptBinaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptBinaryData'
type EncryptionService_EncryptBinaryData_Call struct {
	*mock.Call
}

// EncryptBinaryData is a helper method to define mock.On call
//   - binaryData *model.BinaryData
func (_e *EncryptionService_Expecter) EncryptBinaryData(binaryData interface{}) *EncryptionService_EncryptBinaryData_Call {
	return &EncryptionService_EncryptBinaryData_Call{Call: _e.mock.On("EncryptBinaryData", binaryData)}
}

func (_c *EncryptionService_EncryptBinaryData_Call) Run(run func(binaryData *model.BinaryData)) *EncryptionService_EncryptBinaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.BinaryData))
	})
	return _c
}

func (_c *EncryptionService_EncryptBinaryData_Call) Return(_a0 error) *EncryptionService_EncryptBinaryData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_EncryptBinaryData_Call) RunAndReturn(run func(*model.BinaryData) error) *EncryptionService_EncryptBinaryData_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptCard provides a mock function with given fields: cardNumber, cardHolder, expiry, cvv
func (_m *EncryptionService) EncryptCard(cardNumber string, cardHolder string, expiry string, cvv string) (string, string, string, string, error) {
	ret := _m.Called(cardNumber, cardHolder, expiry, cvv)

	if len(ret) == 0 {
		panic("no return value specified for EncryptCard")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 string
	var r4 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (string, string, string, string, error)); ok {
		return rf(cardNumber, cardHolder, expiry, cvv)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(cardNumber, cardHolder, expiry, cvv)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) string); ok {
		r1 = rf(cardNumber, cardHolder, expiry, cvv)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string) string); ok {
		r2 = rf(cardNumber, cardHolder, expiry, cvv)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(string, string, string, string) string); ok {
		r3 = rf(cardNumber, cardHolder, expiry, cvv)
	} else {
		r3 = ret.Get(3).(string)
	}

	if rf, ok := ret.Get(4).(func(string, string, string, string) error); ok {
		r4 = rf(cardNumber, cardHolder, expiry, cvv)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// EncryptionService_EncryptCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptCard'
type EncryptionService_EncryptCard_Call struct {
	*mock.Call
}

// EncryptCard is a helper method to define mock.On call
//   - cardNumber string
//   - cardHolder string
//   - expiry string
//   - cvv string
func (_e *EncryptionService_Expecter) EncryptCard(cardNumber interface{}, cardHolder interface{}, expiry interface{}, cvv interface{}) *EncryptionService_EncryptCard_Call {
	return &EncryptionService_EncryptCard_Call{Call: _e.mock.On("EncryptCard", cardNumber, cardHolder, expiry, cvv)}
}

func (_c *EncryptionService_EncryptCard_Call) Run(run func(cardNumber string, cardHolder string, expiry string, cvv string)) *EncryptionService_EncryptCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *EncryptionService_EncryptCard_Call) Return(encryptedCardNumber string, encryptedCardHolder string, encryptedExpiry string, encryptedCVV string, err error) *EncryptionService_EncryptCard_Call {
	_c.Call.Return(encryptedCardNumber, encryptedCardHolder, encryptedExpiry, encryptedCVV, err)
	return _c
}

func (_c *EncryptionService_EncryptCard_Call) RunAndReturn(run func(string, string, string, string) (string, string, string, string, error)) *EncryptionService_EncryptCard_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptCardData provides a mock function with given fields: card
func (_m *EncryptionService) EncryptCardData(card *model.Card) error {
	ret := _m.Called(card)

	if len(ret) == 0 {
		panic("no return value specified for EncryptCardData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Card) error); ok {
		r0 = rf(card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_EncryptCardData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptCardData'
type EncryptionService_EncryptCardData_Call struct {
	*mock.Call
}

// EncryptCardData is a helper method to define mock.On call
//   - card *model.Card
func (_e *EncryptionService_Expecter) EncryptCardData(card interface{}) *EncryptionService_EncryptCardData_Call {
	return &EncryptionService_EncryptCardData_Call{Call: _e.mock.On("EncryptCardData", card)}
}

func (_c *EncryptionService_EncryptCardData_Call) Run(run func(card *model.Card)) *EncryptionService_EncryptCardData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Card))
	})
	return _c
}

func (_c *EncryptionService_EncryptCardData_Call) Return(_a0 error) *EncryptionService_EncryptCardData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_EncryptCardData_Call) RunAndReturn(run func(*model.Card) error) *EncryptionService_EncryptCardData_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptCredential provides a mock function with given fields: credential
func (_m *EncryptionService) EncryptCredential(credential *model.Credential) error {
	ret := _m.Called(credential)

	if len(ret) == 0 {
		panic("no return value specified for EncryptCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Credential) error); ok {
		r0 = rf(credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_EncryptCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptCredential'
type EncryptionService_EncryptCredential_Call struct {
	*mock.Call
}

// EncryptCredential is a helper method to define mock.On call
//   - credential *model.Credential
func (_e *EncryptionService_Expecter) EncryptCredential(credential interface{}) *EncryptionService_EncryptCredential_Call {
	return &EncryptionService_EncryptCredential_Call{Call: _e.mock.On("EncryptCredential", credential)}
}

func (_c *EncryptionService_EncryptCredential_Call) Run(run func(credential *model.Credential)) *EncryptionService_EncryptCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Credential))
	})
	return _c
}

func (_c *EncryptionService_EncryptCredential_Call) Return(_a0 error) *EncryptionService_EncryptCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_EncryptCredential_Call) RunAndReturn(run func(*model.Credential) error) *EncryptionService_EncryptCredential_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptPassword provides a mock function with given fields: password
func (_m *EncryptionService) EncryptPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for EncryptPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptionService_EncryptPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptPassword'
type EncryptionService_EncryptPassword_Call struct {
	*mock.Call
}

// EncryptPassword is a helper method to define mock.On call
//   - password string
func (_e *EncryptionService_Expecter) EncryptPassword(password interface{}) *EncryptionService_EncryptPassword_Call {
	return &EncryptionService_EncryptPassword_Call{Call: _e.mock.On("EncryptPassword", password)}
}

func (_c *EncryptionService_EncryptPassword_Call) Run(run func(password string)) *EncryptionService_EncryptPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EncryptionService_EncryptPassword_Call) Return(_a0 string, _a1 error) *EncryptionService_EncryptPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EncryptionService_EncryptPassword_Call) RunAndReturn(run func(string) (string, error)) *EncryptionService_EncryptPassword_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptText provides a mock function with given fields: text
func (_m *EncryptionService) EncryptText(text string) (string, error) {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for EncryptText")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(text)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptionService_EncryptText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptText'
type EncryptionService_EncryptText_Call struct {
	*mock.Call
}

// EncryptText is a helper method to define mock.On call
//   - text string
func (_e *EncryptionService_Expecter) EncryptText(text interface{}) *EncryptionService_EncryptText_Call {
	return &EncryptionService_EncryptText_Call{Call: _e.mock.On("EncryptText", text)}
}

func (_c *EncryptionService_EncryptText_Call) Run(run func(text string)) *EncryptionService_EncryptText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EncryptionService_EncryptText_Call) Return(_a0 string, _a1 error) *EncryptionService_EncryptText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EncryptionService_EncryptText_Call) RunAndReturn(run func(string) (string, error)) *EncryptionService_EncryptText_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptTextData provides a mock function with given fields: textData
func (_m *EncryptionService) EncryptTextData(textData *model.TextData) error {
	ret := _m.Called(textData)

	if len(ret) == 0 {
		panic("no return value specified for EncryptTextData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.TextData) error); ok {
		r0 = rf(textData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EncryptionService_EncryptTextData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptTextData'
type EncryptionService_EncryptTextData_Call struct {
	*mock.Call
}

// EncryptTextData is a helper method to define mock.On call
//   - textData *model.TextData
func (_e *EncryptionService_Expecter) EncryptTextData(textData interface{}) *EncryptionService_EncryptTextData_Call {
	return &EncryptionService_EncryptTextData_Call{Call: _e.mock.On("EncryptTextData", textData)}
}

func (_c *EncryptionService_EncryptTextData_Call) Run(run func(textData *model.TextData)) *EncryptionService_EncryptTextData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.TextData))
	})
	return _c
}

func (_c *EncryptionService_EncryptTextData_Call) Return(_a0 error) *EncryptionService_EncryptTextData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EncryptionService_EncryptTextData_Call) RunAndReturn(run func(*model.TextData) error) *EncryptionService_EncryptTextData_Call {
	_c.Call.Return(run)
	return _c
}

// NewEncryptionService creates a new instance of EncryptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncryptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EncryptionService {
	mock := &EncryptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
