// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/a-blokhin/goph-keeper/internal/model"
)

// ListTextDataUsecase is an autogenerated mock type for the ListTextDataUsecase type
type ListTextDataUsecase struct {
	mock.Mock
}

type ListTextDataUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ListTextDataUsecase) EXPECT() *ListTextDataUsecase_Expecter {
	return &ListTextDataUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID
func (_m *ListTextDataUsecase) Execute(ctx context.Context, userID string) ([]*model.TextData, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*model.TextData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.TextData, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.TextData); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TextData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTextDataUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListTextDataUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ListTextDataUsecase_Expecter) Execute(ctx interface{}, userID interface{}) *ListTextDataUsecase_Execute_Call {
	return &ListTextDataUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID)}
}

func (_c *ListTextDataUsecase_Execute_Call) Run(run func(ctx context.Context, userID string)) *ListTextDataUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ListTextDataUsecase_Execute_Call) Return(_a0 []*model.TextData, _a1 error) *ListTextDataUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListTextDataUsecase_Execute_Call) RunAndReturn(run func(context.Context, string) ([]*model.TextData, error)) *ListTextDataUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListTextDataUsecase creates a new instance of ListTextDataUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListTextDataUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListTextDataUsecase {
	mock := &ListTextDataUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
