// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/a-blokhin/goph-keeper/internal/model"
)

// ListCardsUsecase is an autogenerated mock type for the ListCardsUsecase type
type ListCardsUsecase struct {
	mock.Mock
}

type ListCardsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ListCardsUsecase) EXPECT() *ListCardsUsecase_Expecter {
	return &ListCardsUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID
func (_m *ListCardsUsecase) Execute(ctx context.Context, userID string) ([]*model.Card, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*model.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Card, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Card); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCardsUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListCardsUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *ListCardsUsecase_Expecter) Execute(ctx interface{}, userID interface{}) *ListCardsUsecase_Execute_Call {
	return &ListCardsUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID)}
}

func (_c *ListCardsUsecase_Execute_Call) Run(run func(ctx context.Context, userID string)) *ListCardsUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ListCardsUsecase_Execute_Call) Return(_a0 []*model.Card, _a1 error) *ListCardsUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListCardsUsecase_Execute_Call) RunAndReturn(run func(context.Context, string) ([]*model.Card, error)) *ListCardsUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListCardsUsecase creates a new instance of ListCardsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListCardsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListCardsUsecase {
	mock := &ListCardsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
